### ISSUE TITLE
Platform movement framerate dependency in acceleration of vector X/Y

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-bugs#6550]
_Please do not reply to closed bug reports. Instead, please file a new report, and make sure you follow all the guidelines and provide any missing information._ Ok!

## Problem description

Sorry, I cannot let this go. After some further deliberation, I'm even more certain that https://github.com/Scirra/Construct-3-bugs/issues/6544 is in fact a bug. To be fair it was all a bit confusingly written and I found some further information, so I wanna try this again.

The issue is **not** that a cube suspended in air behaves different from a cube on the floor, it's that the cube in the air behaves different based on framerate. **This is reproducible with the behavior alone with no events at all**! It doesn't matter if the object is suspended via events or simply jumping or falling. See project below

## Attach a .c3p

[noeventrepro.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/10758644/noeventrepro.c3p.zip)

## Steps to reproduce

1. On a 60hz screen, attempt to doublejump up to the right. You barely cannot make the jump.
2. Switch to a higher framerate or use unlimited mode
3. Now you are able to jump up to the right **with room to spare**

## Observed result

Framerate dependent jumpheight

## Expected result

Framerate independent jumpheight

## More details
I have measured the differences as such:
![image](https://user-images.githubusercontent.com/31101309/219439347-c89400b2-a2da-45b6-9811-3aa21d0c4075.png)
On average the cube on the floor reaches a height of 66px at 60fps, and a height of 65.5px at unlimited fps. So the difference at different framerates is <1px
On average the cube in the air reaches a height of 81px at 60fps, and a height of 66px at unlimited fps. So the difference at different framerates is ~15px

Cubes that jump from a floor are framerate independent, whereas cubes that jump from the air are not.

Mind you, I've tried to also enable/disable the behavior when needed to no avail. You mentioned "This means that an object in free-fall but held in place by event logic gets **one extra tick of gravity applied to it. This is indeed framerate dependent**, but I would argue the flaw is in the event logic". As I demonstrated, no events were used, the platform behaviors build-in doublejump suffers the same problem. (Which I assume under the hood does not much different than setting the vectorY to -jumpstrength)

This gave me an idea however and I found a workaround as such:

![image](https://user-images.githubusercontent.com/31101309/219445784-a9da86ef-0eb6-4cbc-8d6b-bbbed1ab8d93.png)

Which counteracts this one tick of gravity perfectly and fixes the framerate dependence. You can try it with this project
[dependencefixed.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/10759037/dependencefixed.c3p.zip)

This will however need to be done every single time you set the vectorY of an object. Doublejumps, spring objects, explosion impulses, etc. and I think there is no way to fix the build-in doublejump like this at all.

What I believe is happening is that the behavior first processes gravity **including the resulting movement**, then setting the vectorY, all in a single tick. As such the object starts the jump from gravity*dt pixels lower than it should. As dt is higher on lower framerates, the object starts lower and this results in the eventual shorter, framerate dependent jumpheight.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r330 (beta)
Browser: Chrome 110.0.5481.96
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 133 gb
Storage usage (approx): 4.3 gb (3.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by Wackytoaster** [comment]
Another interesting finding
![image](https://user-images.githubusercontent.com/31101309/219645287-7258f293-0819-499b-af23-9ef51611e36a.png)

If I do it like this, the issue still happens. If it were to process 1 extra tick of velocity, it would rather jump higher in this case. So it appears that possibly, at some point an extra tick of gravity is deliberatly added.

I noticed that changing the velocity in general does **not** change the objects animation mode, yet it registers the object as "is jumping". So a cube on floor would still register as "Stopped" and the cube in the air keeps registering as "Falling". Maybe that has some impact?

![image](https://user-images.githubusercontent.com/31101309/219646628-1f6f3e54-373f-4261-95b0-62ced806302d.png)

**Comment by Wackytoaster** [comment]
I did it. I debugged it, I just had to. But this is as far as I can take it since I cannot edit the actual code.

I had a look at the code, and along with a project from r0j0hound ([dropbox.com/s/a5qzfvv7y18c3hy/plat_dt_test.capx](https://www.construct.net/out?u=https%3a%2f%2fwww.dropbox.com%2fs%2fa5qzfvv7y18c3hy%2fplat_dt_test.capx%3fdl%3d1)) I replicated the behavior in construct.

Mode 2 = correct implementation and Mode 3 = how it's done in construct.
![image](https://user-images.githubusercontent.com/31101309/220212134-643e3ec5-b2c2-4de8-a99b-7172dc9ac079.png)


The solution theoretically is just doing a little swicheroo. But I do not know if this breaks a million billion things down the line (I sure hope not)
![image](https://user-images.githubusercontent.com/31101309/220211800-bcdfa132-bbc2-4f7b-b9cd-a58e2ea4ee62.png)

**Comment by WilsonPercival** [comment]
Half a year ago I was trying to replicate the behavior of the platform manually and also noticed that the built-in behavior after the jump gives an extra extra tick, which makes the fall faster than it should be. Therefore, your words make sense.

![aa](https://user-images.githubusercontent.com/91274932/220285262-6d923e7f-89c7-47eb-bfc4-888372c0b302.png)

[custom_platform.zip](https://github.com/Scirra/Construct-3-bugs/files/10791114/custom_platform.zip)

**Comment by alastajj** [comment]
> Half a year ago I was trying to replicate the behavior of the platform manually and also noticed that the built-in behavior after the jump gives an extra extra tick, which makes the fall faster than it should be. Therefore, your words make sense.

That's a nice example! When I change the timescale to 0.5, or 2, there's quite a difference in the jumps between the custom vs platform behavior.

**Comment by AshleyScirra** [comment]
I believe this is indeed caused by the fact that, for the past 10+ years, the Platform behavior has always applied acceleration before adjusting the position. It does indeed cause a small framerate-dependent discrepancy, as after setting the velocity on either axis, it will adjust the velocity by an amount corresponding to `dt` before adjusting the position. So while it does use `dt`, it is processing things in not quite the right order to preserve exact framerate independence (to the extent that can be achieved with floating point precision errors). Issue #6599 appears to be the same thing but on the horizontal axis (which I will check separately).

Unfortunately this is a very thorny problem for backwards compatibility reasons. Firstly the code change suggested is much too simplistic: it needs to be applied on both axes, and the current behavior feeds the outputs of the acceleration functions in to the later movement functions, so a naive change like that will likely break other cases (and there have been endless edge cases over the past 10+ years. Really, endless.)

Secondly, fixing this allows the player to jump higher on a 60 Hz system, which is still by far the most common in use. This could well be a serious breaking change. There are probably thousands of projects out there, including ones originally made in Construct 2 around a decade ago that still occasionally get imported to C3; some of them might have dozens or hundreds of levels; and there may be jumps that the level design assumes are impossible, but suddenly become possible if this issue is fixed. I agree this is a bug, but many users will (and have in the past) take the perspective that they don't care why something got changed, they just see that it broke their game and tell us we should put it back. This puts us in a difficult position. We can add a setting if it's really intractable, but I loathe to do that as in the eyes of a new user it's just a mystery compatibility setting that is difficult to explain, and sometimes people toggle stuff without understanding what it's for and end up with the bug again anyway.

So I think this will need a very careful implementation and roll-out that for maximum testing should be applied at the very beginning of a beta cycle to maximize the amount of testing it gets before it reaches stable. I don't want to act on this right now as we're too far through the current beta cycle, but I will look at addressing it for the next beta cycle. The first few beta releases should give some indication of the level of the backwards compatibility implications and that will help inform precisely what we do to deal with that.

**Comment by AshleyScirra** [comment]
I've rearranged the tick sequence for the next beta to fix this and #6599 - it looks like it's much more consistent now. I'm still concerned about the backwards compatibility impact of this, but there's still most of the release cycle to go so we can see how it goes.
