### ISSUE TITLE
"Every X seconds" seems to be altered by high timescale

### ISSUE THREAD

**Issue by DinoSystem** [Scirra/Construct-bugs#6733]
## Problem description

"Every X seconds" seems to be altered by high timescale.

## Attach a .c3p

[TIMER BUG.zip](https://github.com/Scirra/Construct-bugs/files/10926392/TIMER.BUG.zip)

## Steps to reproduce

1. Run the layout, keeping the 1x timescale (in event sheet).
2. Wait for the time to stop (Variable1 should end up at 60, +1 every 1 sec for 60 sec).
3. Run the layout again, setting timescale to 20x or more.
4. Wait for the time to stop (Variable1 should end up at 60 again, or should it?).
(If it reaches 60, try again, or try with a higher timescale, the bug will eventualy present)

## Observed result

At higher timescale (20x or more, usually), after 60 sec time, Variable1 doesn't reach 60 as supposed to.

## Expected result

After 60 sec time, Variable1 should always reach 60 regardless of timescale.

## More details

If replacing "every 1 sec" with an object's behaviour "Timer" (object's timescale set to "timescale"), the bug doesn't appear (and that's the workaround I use in my project).

**Affected browsers/platforms:** 

Edge, Chrome.

**Affected C3 versions:**

All - bug existed since C2.

## System details

<details><summary>View details</summary>

Device name	LAPTOP-DAOHK829
Processor	Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz   2.50 GHz
Installed RAM	8.00 GB (7.83 GB usable)
Device ID	3FC91B51-E8DD-4CFB-B006-E1141BF1C7B0
Product ID	00325-82098-04728-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

Edition	Windows 11 Home
Version	22H2
Installed on	‎20/‎11/‎2022
OS build	22621.1265
Experience	Windows Feature Experience Pack 1000.22638.1000.0

</details>

**Comment by AshleyScirra** [comment]
It is actually by design that 'Every tick' does not run more than once per tick. (This is documented: https://www.construct.net/en/make-games/manuals/construct-3/system-reference/system-conditions#internalH1Link11:~:text=equals)%2010%20seconds.-,Every%20X%20seconds,-Run%20the%20event)

If you set a time scale of say 100 on a 60 Hz display, then every tick 1.667 seconds of game time is passing. Therefore 'Every 1 second' won't be able to keep up, as it will run at most once every tick.

TBH with such a high time scale many things will stop working - anything that causes extremely large delta-time values will cause all sorts of things to start falling apart since the engine is designed to work in reasonably small steps.
