### ISSUE TITLE
Wrong key name on non-UK keyboards

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-bugs#6795]
Re-posting because I think this is a mistake.

Ashley, I understand you have a UK keyboard, but people from most other countries are using variations of US International keyboards where the key with code 222 is a single quote (')

![image](https://user-images.githubusercontent.com/36763350/225666415-64788934-4e51-422f-b97c-78ec054eb801.png)

Javascript detects and shows it correctly:

![image](https://user-images.githubusercontent.com/36763350/225796378-1caea9ba-d70d-4224-8cf5-ab89a24cc47d.png)

Construct 2 shows it correctly:

![image](https://user-images.githubusercontent.com/91274932/225670838-7459c571-24f7-4d8e-91b7-1456c5d6e764.png)

However, Construct 3 displays it as "#" in the event sheet and in Keyboard.StringFromKeyCode expression, which is wrong:

![image](https://user-images.githubusercontent.com/36763350/225796954-82ea8abd-4e6f-482a-9614-e8764dd2b077.png)

## Attach a .c3p

[KeyNameIssue.zip](https://github.com/Scirra/Construct-bugs/files/10997281/KeyNameIssue.zip)

**Comment by AshleyScirra** [comment]
I don't think this is feasible to fix because there are dozens of keyboard layouts around the world, they all work slightly differently, and so it's not possible to always automatically determine the name of a key pressed. For example if I made a change here, then it would make the UK keyboard layout wrong, and someone else could file the same bug but in reverse. Construct makes a best effort and it may be wrong, but I don't think we can do any better.
