### ISSUE TITLE
Audio playback fails/does not work correctly on any iOS or macOS in browser

### ISSUE THREAD

**Issue by calminthenight** [Scirra/Construct-bugs#6801]
## Problem description

Audio playback in HTML5 export does not work as expected in iOS (all versions, Safari and Chrome) and macOS (Big Sur 11.6 only tested).

## Attach a .c3p

.CP3 and exported HTML5 attached: 
https://1drv.ms/u/s!AkmrWgxeuxlKhJ8FKIQHl-UlbsxHNw?e=dcfxlf

## Steps to reproduce

1. Host exported demo project as HTML5 web app on server
2. Load app and touch anywhere on screen to begin playback.

## Observed result

On Safari 16.3.1 on macOS 11.6 and 11.7.4 audio will not play immediately (despite being set to stream from music folder). There is a long delay before it begins. This delay extends well beyond the file being loaded into RAM. **The issue also occurs when played from the Sounds folder.

On iOS (all versions) in Safari, once the user attempts to play the music, no sound will play and Safari will shortly refresh the page. This will continue forever with no audio ever played. No useful information is found in the logs.

On iOS (all versions) in Chrome, once the user attempts to play the music, no sound will play and Chrome will shortly refresh the page, several times before crashing. No useful information is found in the logs.

## Expected result

Music should begin to play almost immediately. (This is the case in Chrome, edge etc. for windows machines and android devices)

FYI: 
Building a simple JavaScript app that does similar works in all these browsers.
Using a .mp3 file and loading it from a URL makes no difference to the results.

## More details

Issue affects iOS and macOS.

Safari and Chrome on iOS. Safari on macOS.

R327.3 (but untested on previous versions)

## System details

N/A

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
The problem is mainly that the audio track is very long at 1 hour. This is much longer than most audio tracks (most music tracks are just a few minutes long).

Due to a mix of Safari missing features and bugs, at the moment we are forced to fully download and decode all audio in Safari before playback can begin. This explains the wait before playback can begin, and the fact the page crashes: a fully decompressed 1 hour stereo track will use at least 600mb of memory, possibly double that (1.2 GB) with a float32 representation. If the device cannot fit that in memory then it will either fail to play the audio or crash the tab.

Unfortunately we can't do better than that in Safari at the moment due to the aforementioned issues. If Safari iOS supported WebM Opus - which all other browsers do, including Safari on macOS but mysteriously not on iOS (with no word from Apple as to why or when it will be supported) - then this wouldn't be a problem; we'd use the browser built-in streaming audio playback. However as Safari iOS doesn't support that we have to ship our own WebM Opus decoder, which due to the implementation complexity, does not support streaming. And despite the fact Safari on macOS does support WebM Opus, at the moment we have it turned off to work around [this bug](https://bugs.webkit.org/show_bug.cgi?id=245428) that breaks audio playback; so far there is no response from Apple on that, and in the mean time we've had to switch Safari on macOS over to our own decoder as well.

Providing Apple support WebM Opus like every other browser, and fixes remaining bugs in its implementation, then we can switch over to using Safari's built-in support and all these issues will be solved. However until then I'm afraid further improvements are not feasible.

**Comment by calminthenight** [comment]
I think the issue actually does lie with Construct. In this case it was a commercial project and I had a deadline so I rebuilt the app in JavaScript and it works fine.

Using JavaScript there was no delay or issues playing back the same audio files in the browsers, apart from the older versions of Safari where .webm was not supported. The files would start immediately and play normally. No excessive memory use was seen.

I switched to .mp3 in the Javascript project just for maximum compatibility. Using .mp3 in Construct presented the same issues, so it is not a .webm compatability issue.

I believe there is an issue with C3's implementation of WebAudio API.

If you want I can provide a simple JS app showing it working correctly?

**Comment by AshleyScirra** [comment]
I've explained what's going on with Construct - sure, your own code may not run in to the same issues Construct does, but unfortunately that doesn't change anything on our side.

**Comment by AshleyScirra** [comment]
So long as the individual music tracks are all relatively short - e.g. 5 minutes or less - everything should work fine.

**Comment by calminthenight** [comment]
Ok, thanks.
