### ISSUE TITLE
C3P file corrupted, just lost 10+h of progress

### ISSUE THREAD

**Issue by Grendya** [Scirra/Construct-bugs#6810]
![image](https://user-images.githubusercontent.com/109753997/226482199-2a26bc79-84a5-48ee-9226-0c48ce8a034b.png)
Whenever I try to open the project I get this message. I've tried opening it from Opera and Chrome and nothing. I used F12 to see what was wrong, apparently it's the name I gave a function. After creating it it stopped working, so I reset Construct to see if it would get fixed but now I can't even open the project. 

![image](https://user-images.githubusercontent.com/109753997/226482565-9dbdf248-20f8-4097-a61c-3c74fae6fb9e.png)

C3P attached: [Attach a .c3p](https://drive.google.com/file/d/1W2JZOI2JWtjU0KlqBdV7J_oyWlzlX2HX/view?usp=sharing)
This is the only thing I could send since I can't exactly open the project.

1. I was trying to clean my code a bit so I created a couple of functions, "PL1 Reset" and "PL2 Reset".
2. I gave them the exact same code that had worked earlier without a function.
3. Tried to test it but the preview would not load, it worked fine right before creating the functions.
4. I restarted Construct but couldn't open the file again, I got the error code I said before.
 
I expected it to work fine, it was just a function.

## More details
Tested on both Opera and Chrome and nothing. Tried to downgrade Construct but couldn't open the file since it's a r327.3 file in a r327.2 version. r372.3 had been working fine until now.

**Comment by GameSoul7Eugene** [comment]
@Grendya, I fixed your project's integrity. It should now successfully open: [Download fixed project](https://drive.google.com/file/d/1dIrF29sLgAQFTqQGJp4fGANDKcNXiOku/view?usp=share_link)

This issue can be closed.

**Comment by AshleyScirra** [comment]
I'm afraid as per the bug report guidelines, without steps to reproduce there is no way to investigate this any further, so closing. It is also possible it's an issue we already fixed in the latest beta.

Construct has built-in backup options that can help protect your work in the event of software or hardware failure, or disasters such as fire, flood, theft, and ransomware. However you must enable them first in Settings. Keeping regular backups is strongly advisable for any important digital work in any software.
