### ISSUE TITLE
Family overlap workaround + custom actions is bugged

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-bugs#6821]
## Problem description

One of constructs quirks is that objects cannot check if they are overlapping their own instances, e.g. "is sprite 1 overlapping sprite 1" and in my case also "is family1 overlapping family1". A common workaround is to essentially duplicate the family and then check "is family1 overlapping family2". This is ok, but custom actions do not function properly with this workaround, specifically picking by UID.

## Attach a .c3p

[ABfamilies.c3p.zip](https://github.com/Scirra/Construct-bugs/files/11040626/ABfamilies.c3p.zip)

## Steps to reproduce

1. Drag the upper red square on each green square
2. Both the red&green square that overlap start rotating (this is expected behavior)
3. Drag the middle/bottom red square on each green square
4. Some green squares do not rotate, but the red square rotates twice as fast instead.
5. (Optional) Drag the middle red square on the upper and lower red square
6. When overlapping the upper red square, only the upper red square rotates normally, the dragged one rotates twice as fast. However, when overlapping the bottom red square, the dragged red square rotates normal, but the bottom red square rotates twice as fast.

## Observed result / Expected result

On paper, the expected result would be that the squares all rotate at twice the defined speed, as the custom action would be called twice for each square. Once for the square as "Sprite1" and once for the square as "familyB".

## More details
Taking the rotation out of the custom action and simply executing it inside the overlap condition directly works as expected, as in the squares rotate at twice the defined speed.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r335 (beta)
Browser: Chrome 111.0.5563.66
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 133 gb
Storage usage (approx): 4.3 gb (3.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by OverboyDev** [comment]
Yep it seems to happen not only while overlapping Families using this trick but also in the other situations involving this Family Picking trick.

**Comment by AshleyScirra** [comment]
The provided project seems over-complicated to me. Custom actions essentially run with 'Copy picked', and the whole point of that feature is to avoid the need to use the old-style passing a UID as a parameter, which this example still does. You can instead rely on the picking continuing to the custom action and do it in a much simpler way like this: [issue6821.zip](https://github.com/Scirra/Construct-bugs/files/11214495/issue6821.zip)
That demonstrates it working identically with and without custom actions.

It's hard to figure out what's meant to happen in the provided project - the way it's set up, the override either will or won't be used depending on which way round the family "A overlaps B" condition works. If that works out as "Sprite overlaps Sprite2" or "Sprite overlaps Sprite", then it will use the Sprite override, but if that works out as "Sprite2 overlaps Sprite" or "Sprite2 overlaps Sprite2" then it won't use the override, and it's not clear as a user what Construct will do (nor do I think it makes sense to specify what happens in that case, as the point of a family is it doesn't matter which you get). The override sub-event that modifies the family B based on the passed UID makes this further confusing, as I think it's possible it does in fact modify the same instance again depending how the picking works out. All in all this setup is a bit of a mess.

If I add a much simpler override to my own example: [issue6821-b.zip](https://github.com/Scirra/Construct-bugs/files/11214601/issue6821-b.zip)
It does work consistently between the red and green sprites. Red v Red overlap doesn't rotate as both use the override, but Red v Green or Green v Green overlap does rotate both sprites. Why does it rotate the Red in a Red v Green overlap even when it has an override? I think it's because in that case, the green sprite is A and the red sprite is B, so it runs the family custom action and rotates B, which rotates the red one.

So overall I'm not convinced the original project demonstrates a bug. I think it's just a particularly confusing way to combine families, overlaps and custom actions.
