### ISSUE TITLE
Bug Drag and Drop

### ISSUE THREAD

**Issue by M4riot** [Scirra/Construct-bugs#6900]
## Problem description
When starting the Layout the drag functionalities are not working, but if you start the layout that has direct drag and drop it works

## Attach a .c3p
https://www.dropbox.com/s/o9np2zqbk1dyn20/Bug.zip?dl=0

## Steps to reproduce

1.Launch the project from the Start page and click the Start button
2.Try dragging the words in sprites down the next page
3.Open the direct layout that has drag and drop and try to drag

## Observed result
Sprites are not dragged

## Expected result
After changing the layout, it was expected that the objects would be dragged

## More details
That the objects are dragged and when positioned and released on the right place they go up 1 point and delete that dragged object and the other object appears

**Affected browsers/platforms:** 
All

now

**First affected release:** 
now

## System details
When starting the main layout numbers between 1 and 2 are randomized and saved in a global variable, to start a phase page it compares the variable number when clicking on the start button, inside the phase there are options to drag and drop in the right places and increase the number of points, when you finish all of them you should send them to the next phase

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by WilsonPercival** [comment]
@M4riot  This is a bug in your events. In the eleventh event, you have written that if the variable is equal to one, then go to the layout. When you run the `Start` layout, the number 1 is written to the variable. Therefore, when moving to the next layout, it constantly jumps to the same layout. That's why you can't move the sprite.

![aaa](https://user-images.githubusercontent.com/91274932/231255874-5001b15a-c580-4a21-92c2-9c4c5c98cc61.png)

**Comment by AshleyScirra** [comment]
I would guess this is a mistake in your events, but it's not a minimal project so it's hard to figure out what's going on - as per the bug report guidelines we need a minimal project to be able to investigate.
