### ISSUE TITLE
CocoaPods "Pods" folder missing in exports for Xcode - Build service issue?

### ISSUE THREAD

**Issue by therealPaulPlay** [Scirra/Construct-bugs#6901]
## Problem description

CocoaPods is used to bundle Swift and Objective-C files inside of Construct games for IOS and iPad OS. However, now the "Pods" folder is compeltely missing in the Xcode project folder, which makes the entire export unusable if you use plugins such as a Google Ads plugin. 

## Attach a .c3p
This happens with many addons that need cocoapods because they use some kind of SDK written in swift or objective-c. 
[TestprojectNoPodsFolder.zip](https://github.com/Scirra/Construct-bugs/files/11203236/TestprojectNoPodsFolder.zip)

## Steps to reproduce

1. Create a new Construct project with addons that use 3rd party SDKs. 

3. Export the project to IOS and select the Xcode Export

5. The "Pods" folder is missing completely and there are countless reference errors and the project cannot be built. 

## Observed result

Cocoapods does not work with the build service. The folder is completely missing, only these files exist: 
pods-debug.xcconfig
pods-release.xcconfig
pods.json
PodsJson.js

## Expected result

CocoaPods should generate a Pods folder and load all SDKs or Frameworks as usual. 

## More details
r336 stable, however this is a build service realted issue

## System details

M1 Macbook Air or Windows Desktop PC. Running an old version of Chromium on my PC and the newest Chrome version on my macbook. 

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It's difficult to tell what's going on here, especially as the project uses a third-party addon, which usually means we do not investigate reports as it could be the third-party addon that causes the problem (see the bug report guidelines). Did this used to work? Did a Construct update stop it working? Was the third-party plugin updated and then it stopped working? Does it work if you do a Cordova export and then build the Xcode project yourself? These are all key questions.

Construct's official Mobile Advert plugin uses cocoapods and if I do an Xcode export with a project with Mobile Advert, it returns a zip file that correctly includes the Pods folder. This would appear to indicate to me that the build server is in fact working properly, as if the problem was with the build server, then this case would not have produced a Pods folder, but it worked OK. So perhaps the third-party addon is misconfigured or incompatible somehow? I would advise that you report this to the addon developer. As I don't think there's anything for us to do on our side here, closing this issue.

**Comment by AshleyScirra** [comment]
The changelog for r330 doesn't include any significant changes for Cordova. The only listed Cordova change in that release is that a parameter listed in the documentation as optional was in fact required, and the fix made it actually optional, which is unlikely to have had any functional difference (as previously it was mandatory so callers would have had to specify it). So I am skeptical that release actually changed it - perhaps something else changed.

**Comment by therealPaulPlay** [comment]
Yeah, good to hear, I unfortunately have no idea what could cause this. However, maybe the developer will find out the issue. It could also be related to my project settings or sth (he said that he made an xcode build just last week and it worked) but I can‘t see that really making a difference. But bugs can be quite weird sometimes ;)
