### ISSUE TITLE
Whitelist request (routine)

### ISSUE THREAD

**Issue by Chadori** [Scirra/Construct-bugs#6930]
Hi,

Would you please whitelist the following plugins:

```JS
community-admob-plus-cordova@1.29.3
Reason: We need Google Admob iOS SDK version 9.3.0 to fix build failures using other SDKs, for example Firebase.

onesignal-cordova-plugin@3.3.1
Reason: Outdated Cordova plugin, so many changes in the API including deprecations and required permission changes.
```

Thank you.

**Comment by AshleyScirra** [comment]
This does not appear to be urgent:

- `community-admob-plus-cordova` has no existing entry on the allowlist, so this is a request for an entirely new plugin, not an update to an existing one. If it is a fork of an existing plugin, please indicate which one, and also explain why a fork is necessary (it is much preferred to update the original plugin instead of forking, as forks multiply the amount of review work we have to do).
- `onesignal-cordova-plugin` looks like a routine update.

**Comment by Chadori** [comment]
Hi @AshleyScirra,  

The `community-admob-plus-cordova` is urgent because we cannot build other Google plugins anymore, for example Firebase Analytics, due to conflicting versions. Firebase Analytics require at least `9.3.0` to build while `cordova-admob-plus` is still stuck in `8.13.0`.

The `onesignal-cordova-plugin` is needed because we cannot launch the permission dialog, which is required now for Android to run the plugin for new users.

**Comment by AshleyScirra** [comment]
Added `community-admob-plus-cordova@1.29.3` and `onesignal-cordova-plugin@3.3.1` to allowlist.
