### ISSUE TITLE
Inconsistent Platform jump results

### ISSUE THREAD

**Issue by Kapusta-dev** [Scirra/Construct-bugs#6975]
## Problem description

When manually jumping from a set x-position with a set jump strength, the player will land in a variety of different locations rather than a consistent single spot. Tested on r339 with the latest platforming bug fixes.  

## Attach a .c3p

[PlatformerJumpBug.zip](https://github.com/Scirra/Construct-bugs/files/11323486/PlatformerJumpBug.zip)

## Steps to reproduce

1. Launch preview
2. Press Q - wait two seconds for the player to jump and land. Note the position landed.
3. Press Q to repeat and keep repeating until the player lands in a different spot. Takes 3-8 tries usually.

## Observed result

The player will land in a variety of different locations throughout testing.

## Expected result

The player should land in the exact same spot every time since position and jump strength never change.

## More details

**Affected browsers/platforms:** 

All platforms affected. This was happening since last year so many releases affected. 

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r339 (beta)
Browser: Chrome 112.0.5615.138
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 133 gb
Storage usage (approx): 154 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by Kapusta-dev** [comment]
Looks like this is once more a refresh rate issue.
It happens under 120Hz +, but it doesn't happen on 60Hz even in full frames mode. 

![IssueReproduced](https://user-images.githubusercontent.com/67970011/234318992-05a07976-4807-4a96-86d5-6a6250a5d415.gif)

A different issue happens on 60Hz where the player will land on the very edge, stop, and then drop down.

![IssueReproduced2](https://user-images.githubusercontent.com/67970011/234319555-c65905d1-6a40-41b8-b413-646c03000da2.gif)


I hoped the framerate independence fix would solve these two bugs but looks like no luck there.
I've been battling these specific two bugs for over a year now so if there is any more information I can provide to help reproduce this on your end please let me know.

**Comment by AshleyScirra** [comment]
This project appears to use a carefully designed setup with a tiny clearance to an obstacle. Whether the player hits the obstacle ends up depending on extremely small changes in the movement. A more fair test is like this where it never collides with an obstacle: [issue6975.zip](https://github.com/Scirra/Construct-bugs/files/11324571/issue6975.zip)

With this test I get the following results:
Vsynced 60 FPS: ends at 136.4
Unlimited at 5000-10000 FPS: ends at 134.9
That's a difference of about 1.5px with a framerate that varies by thousands of FPS.

I think this comes down to two other causes of imprecision in movement:

1) Floating point calculations: these simply are not perfectly accurate, and the inaccuracy literally happens in the CPU circuitry, as it's only possible to work with finite amounts of precision. Movement over a different number of frames will produce a slightly different result due to the way rounding and precision error occurs through all the different calculations.
2) The jump distance in a case like this also depends on the precise time the player hits the floor. All movements happen in small steps every frame, and the size of the step depends on `dt`. When the Platform behavior hits the floor, it usually actually steps some way in to the floor; then the logic of the platform movement pushes it upwards so it lands on top of the floor. In this project it also sets the movement vector X until that happens at which point it sets it to 0. So then the amount of horizontal movement depends on exactly when the player hits the floor. Consider at a low FPS, the platform behavior is more likely to step a long way in to the floor, by which time it has also moved further horizontally. However at a high FPS, especially unlimited and running at something like 5000 FPS, each frame is moving in extremely small steps, and so it will only step a tiny distance in to the floor - at which point it also stops horizontal movement according to the project's logic. This essentially causes the horizontal movement to stop sooner, which explains why the unlimited FPS result does not move quite as far.

I think these points are more or less infeasible to fix. Floating point imprecision is fundamental to computing, and the fact movements step with delta-time precision is fundamental to per-frame ticking logic which is how most things in Construct work. As of r338 I'm pretty sure the Platform movement is doing the right calculations, but properly handling dt does not overcome floating-point precision errors or the fact movements have to-the-nearest-frame resolution. These are things that will affect any game engine doing the same thing, as it's fundamental to moving things per frame. Therefore I don't think we can take further action here, so closing as wontfix.

My advice would be to either: design levels not to rely on extreme levels of precision, as game engines don't usually provide exact results due to things like floating point precision errors and nearest-frame logic; alternatively if you really do need something to land at an *exact* co-ordinate, then fake it: set the position when it lands, or use something like a tween to animate towards an exact position without relying on a collision-detecting movement like Platform.
