### ISSUE TITLE
Set character height action is missing

### ISSUE THREAD

**Issue by yojona** [Scirra/Construct-bugs#7074]
## Problem description
There is not an action for `Set character height` in the SpriteFont object, there is only the `Set character width` action.

This is a screenshot from Action Dialog in the editor:
![image](https://github.com/Scirra/Construct-bugs/assets/13840865/77c6e812-7be8-4456-9a4c-ba2a4b31db81)

This is problematic cause I need to change some chars width and height for Hangul characters at runtime

## Attach a .c3p
[FontCharSize.zip](https://github.com/Scirra/Construct-bugs/files/11590580/FontCharSize.zip)

## Steps to reproduce

1. Add SpriteFont object to the project
2. Add "On Start of Layout" event or any other event to the Eventsheet
3. Click on `Add Action`
4. Click on `Font`
5. Go to `Appearance`

## Observed result
There is not an action for `Set character height`

## Expected result

Find actions to set the width and height of characters

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is currently by design as "set character width" changes not the size of the actual character, but the amount of horizontal space it takes up for text layout. This allows making a character like "i" take up less space than "W". I'm not sure what you expect your proposed action to do, because setting the vertical height doesn't apply to this, at least when using a horizontal writing direction.

You can already change the visible width and height of individual characters using BBcode scale tags like `[scalex=2]`, `[scaley=2]` or `[scale=2]`, as [noted in the manual](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/sprite-font). If you are asking for a new feature, such as vertical writing direction support, please post to the suggestions platform instead.
