### ISSUE TITLE
Pin + Revolute joint results in a spinning object

### ISSUE THREAD

**Issue by therealPaulPlay** [Scirra/Construct-bugs#7081]
## Problem description

When you hinge an object with the physics behavior to another one and then add the pin behavior and pin it to an image point of the other physics object, it will start to spin. 

## Attach a .c3p

Please refer to the example in the middle. 

[ConstructBugExample.zip](https://github.com/Scirra/Construct-bugs/files/11600758/ConstructBugExample.zip)

## Steps to reproduce
1. create a new physics object
2. create a second physics object and hinge it to the first one
3. add the pin behavior to the second object and pin it to an image point of the first object

## Observed result
The second object starts spinning.

## Expected result

It should not spin. 

## More details
Newest stable release.

## System details

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I don't think this is a sensible thing to do - this setup means there are two behaviors trying to do conflicting things: the Physics behavior is trying to simulate realistic physics with a joint and the Pin behavior is ignoring that and trying to keep things in a fixed position. Since they are trying to do conflicting things I don't believe it's worth trying to investigate or change what is happening. The best advice is "don't do that", which is pretty much what the [Physics basics tutorial says](https://www.construct.net/en/tutorials/physics-construct-basics-6)

**Comment by therealPaulPlay** [comment]
I can understand that but there are certain cases in which there is no other way to achieve certain things.
