### ISSUE TITLE
Character teleports down on 400 pixels when I roll or attack downstairs. This bug appeared after r344 release

### ISSUE THREAD

**Issue by ANT-games** [Scirra/Construct-bugs#7091]
## Problem description
When I roll or attack downstairs player teleports down the layout and it's very strange. I notice that on a lot of high layouts.

## Awita_bug.c3p
[Awita_bug.zip](https://github.com/Scirra/Construct-bugs/files/11644225/Awita_bug.zip)

## Steps to reproduce

1. Preview cave3 or forest1 layouts
2. Find the stairs which locate the highest
3. try to roll or attack downstairs

## Observed result
When I roll or attack downstairs character teleports down the layout and it's very strange. I notice that on a lot of high layouts. 

## Expected result

When I attack or roll downstairs character has just to do it, without teleportation on 400 pixels down.

## More details
It appeared after r344 update. 

**Affected browsers/platforms:** Construct popup window preview on Construct desktop and also I tried in Crome

**First affected release:** All worked normally before r344 update

## System details

<details><summary>View details</summary>
Tried on different computers

</details>

A few videos with bugs, all appeared after r344 release.
https://imgur.com/a/zVOaonK

Controls
Move- Arrow keys
Jump- Space
Attack- C
Roll - X

**Comment by WilsonPercival** [comment]
@AshleyScirra @ANT-games I have simplified the project.

[issue7091.zip](https://github.com/Scirra/Construct-bugs/files/11645657/issue7091.zip)

Steps to reproduce:

1. Open and run the project.
2. Hold down the `D` key to move the character to the right.

Observed Result: The character is teleported to the lower platform.

Expected Result: The character is not teleported to the lower platform.

https://github.com/Scirra/Construct-bugs/assets/91274932/625eeece-881a-4b30-b512-9fde3b8292b4

I'm not sure if I can make a minimal project, because after removing the bottom platform, the bug disappears.

**Comment by AshleyScirra** [comment]
This project sets the vector X to 100x the maximum speed - 33300 when the maximum speed is 330. It seems to work fine if you set the vector X to just 330. Why not just do that? If you set things to extreme values, it can often cause problems, as the engine expects things to work within reasonable tolerances.
