### ISSUE TITLE
QR code object does not support hierarchy

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-bugs#7118]
## Problem description

The QR code object can be created with the hierarchy it has via action, but you cannot add any hierarchy in the layout view.
![image](https://github.com/Scirra/Construct-bugs/assets/7268697/6e76f712-36a5-418c-9210-bb7ed9cc752f)

This is either a bug or maybe overlooked functionality. The QR code plugin cannot be added as a child in a hierarchy (menu item not there). Also the z elevation is missing. 

It would help a lot to be able to spawn this on certain panels and such, via the use of the hierarchy.
This functionality would help a lot with making the plugin more easily usable for game scenarios (rather than app scenarios). 

![image](https://github.com/Scirra/Construct-bugs/assets/7268697/f92b30d2-1179-4c5d-9804-48f53eae9642)

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** r344.2

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by GameSoul7Eugene** [comment]
I believe that the QR Code plugin (as well as the User Media and Video plugins) cannot be used in a hierarchy because they don't support the Z elevation and angle properties. Therefore, they are unable to inherit these properties from other plugins that do.

**Comment by AshleyScirra** [comment]
The "Create hierarchy" option of 'Create object' is a red herring: it's always shown regardless of whether the object supports hierarchies, so it's irrelevant to this issue.

I'm not sure I understand why you said "Also the z-index is missing" when your screenshot does show the Z index for a QR code object?

So as far as I can tell this issue is just "The QR code object does not support being added to a hierarchy" - @DiegoScirra can you take a look as to why it doesn't support it?

**Comment by AshleyScirra** [comment]
It turns out there just needed to be a flag added to enable hierarchy support, so that is done for the next beta.

**Comment by JeFawk** [comment]
Awesome! Thank you!
