### ISSUE TITLE
Hierarchy tween angle out of sync bug

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-bugs#7132]
## Problem description

I have a hierarchy with `Sprite_Parent` and `Sprite_Child` sprites. They have a `Tween` behavior that I use to animate the `Angle`.

The parent has a time of `0.2` seconds with a final angle value of `45` degrees.
The child has a time of `0.4` seconds with an end angle of `90` degrees.

The video shows what happens out of sync. It lies in the fact that the parent sprite and the child sprite after some time begin to move, creating a chaotic pattern from the train.

On the right, I demonstrated how I think it should be.

## Attach a .c3p

[hierarchy_tween_angle_out_of_sync_bug_r346b.zip](https://github.com/WilsonPercival/WilsonPercival/files/11811943/hierarchy_tween_angle_out_of_sync_bug_r346b.zip)

## Steps to reproduce

1. Open and run the project.
2. Press '1'.

## Observed result

https://github.com/WilsonPercival/WilsonPercival/assets/91274932/6ad133b5-d353-4c32-a1f0-025e79dadb3f

## Expected result

Sprites should not create a chaotic pattern over time.

## More details

**Affected browsers/platforms:** Mozilla

**First affected release:** broke in r346b

## System details

<details><summary>View details</summary>

Platform information

Product: Construct 3 r346 (beta)
Browser: Firefox 114.0
Browser engine: Gecko
Context: browser
Operating system: Windows 7
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:109.0) Gecko/20100101 Firefox/114.0
Language setting: en-US
Local storage

Storage quota (approx): 9.8 gb
Storage usage (approx): 347 mb (3.5%)
Persistant storage: No
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to bug 1163426
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    UI effects are disabled in settings.
    Determining input device capabilities is not supported.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_bptc
    EXT_texture_compression_rgtc
    EXT_texture_filter_anisotropic
    OES_draw_buffers_indexed
    OES_texture_float_linear
    OVR_multiview2
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context
    WEBGL_provoking_vertex

Audio information

System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)
    WebM Vorbis (audio/webm; codecs=vorbis)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm; codecs=av01.0.00M.08)
    MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
The problem with tweens (and timelines) slowly becoming out of sync will be resolved when the next release cycle starts.

The two animations in the example will still be different though, because they are doing slightly different things.

Tweens apply their changes relative to the existing state of an instance. In the example, as the parent changes it's angle, the change affects the child, when the child changes it's own angle, that change is applied on top of the change that was already produced by the parent changing.

The animation in the script changes the parent which affects the child but then makes an absolute change to the child. That means that the child ends up with the angle it needs to have so it's absolute transformation is the number that was passed in. That is a slight but meaningful difference.

There isn't a clean way to produce a similar result with the current tools, you can do it if you create two timelines (one for each instance) and make sure to use the **"Absolute"** result mode in the **"Angle"** track of the child timeline.

Playing both timelines at once will produce almost identical results as the scripted animation.

[hierarchy_tween_angle_out_of_sync_fix.zip](https://github.com/Scirra/Construct-bugs/files/14194689/hierarchy_tween_angle_out_of_sync_fix.zip)

Keep in mind this example will only start working properly when the next release cycle starts, but in it you can see how the timelines are setup.

**Comment by WilsonPercival** [comment]
> The problem with tweens (and timelines) slowly becoming out of sync will be resolved when the next release cycle starts.
> 
> The two animations in the example will still be different though, because they are doing slightly different things.
> 
> Tweens apply their changes relative to the existing state of an instance. In the example, as the parent changes it's angle, the change affects the child, when the child changes it's own angle, that change is applied on top of the change that was already produced by the parent changing.
> 
> The animation in the script changes the parent which affects the child but then makes an absolute change to the child. That means that the child ends up with the angle it needs to have so it's absolute transformation is the number that was passed in. That is a slight but meaningful difference.
> 
> There isn't a clean way to produce a similar result with the current tools. You can do it if you create two timelines (one for each instance) and make sure to use the **"Absolute"** result mode in the **"Angle"** track of the child timeline.
> 
> Playing both timelines at once will produce almost identical results as the scripted animation.
> 
> [hierarchy_tween_angle_out_of_sync_fix.zip](https://github.com/Scirra/Construct-bugs/files/14194689/hierarchy_tween_angle_out_of_sync_fix.zip)
> 
> Keep in mind this example will only start working properly when the next release cycle starts, for now you can see how the timelines are setup in the editor.

@DiegoScirra Understood thanks.
