### ISSUE TITLE
Safe mode still shows an error if it fails to fetch URL of a developer mode addon

### ISSUE THREAD

**Issue by OverboyDev** [Scirra/Construct-bugs#7230]
## Problem description

Safe mode still shows an error if it fails to fetch URL of a developer mode addon.
This is a very annoying issue because there is no way to uninstall the addon causing the error in safe mode while the point of this safe mode is exactly to handle this kind of situation.

## C3P

No c3p because it's not related to c3p but addon installed via developer mode

## Steps

1. Add a developer addon with a local web server
2. Turn the local web server off
3. Both regular mode and safe mode crash with an error, so **there is no way to uninstall the addon, even in safe mode !

## Observed result

There is no way to get rid of the developer addon 

![chrome_73Zqhzockd](https://github.com/Scirra/Construct-bugs/assets/99751718/13decb68-8f80-41a6-9be2-9bf5b67cb200)

## Expected result

In safe mode, it shouldn't show an error, we should just be able to uninstall the developer addon via 

## More details

If the safe mode can't remember the name of the developer addon which it can't fetch the URL, then its name should probably just be "http://localhost:5500/addon.json".

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It is actually very complicated to support this in the editor, because if it can't even fetch addon.json, then there is literally nothing known about the addon whatsoever. Even listing it in the addon manager and providing tools to modify a mystery addon would probably require a lot of special case coding in an already-complicated part of Construct. Meanwhile it seems reasonable to me to say: just leave your local web server running, or re-start it. Alternatively clear your browser storage. Or if you really want to be surgical about it, open dev tools, go to IndexedDB, open the localforage database for editor.construct.net, and delete the key `c3-dev-addon-list`, which will wipe all installed developer mode addons.
