### ISSUE TITLE
Typo in Fade behavior

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-bugs#7254]
You can disable the fade behavior from working, but it's unclear how to enable it with actions.

![image](https://github.com/Scirra/Construct-bugs/assets/5744908/f31bb2d3-f7f3-4eef-b97d-82600b8edaba)

![image](https://github.com/Scirra/Construct-bugs/assets/5744908/d98e5b2e-3e05-4ea6-9e44-6dbb38f39608)

I think the description for "start fade" might be clearer if it said "not **_enabled_** on start"

That way there is a link between the "enabled" and the "start fade". 

__________

An alternative to better link them, could be to replace the word "Enabled" with "Active".

Because disabling behaviors normally requires an action to "enable" them to work. Whereas, the Fade behavior is a confusing exception. 

____________

thanks!

**Comment by AshleyScirra** [comment]
Looks pretty similar to #1799 - the Fade behavior just uses 'Start fade' instead of 'Set enabled', which arguably is a clearer name for what it actually does especially as it does not merely toggle an enabled setting (there is other logic it runs when starting a fade). IIRC it actually did originally have the property named "Active", and someone reported that as inconsistent with other behaviors, so we renamed it to "enabled", and I don't think it's worth reversing that. Also renaming core features that have been in use for many years causes problems with making tutorials, manual entries, lesson plans etc. go out of date and need updating, so I generally avoid that wherever possible.

TBH the Fade behavior is pretty much made redundant by the Tween behavior, as a fade is just a special case of an opacity tween. So I'd rather not touch the Fade behavior, and I'd probably deprecate it if it wouldn't cause such a problem with things like tutorials as I mentioned.

**Comment by WilsonPercival** [comment]
> Looks pretty similar to #1799 - the Fade behavior just uses 'Start fade' instead of 'Set enabled', which arguably is a clearer name for what it actually does especially as it does not merely toggle an enabled setting (there is other logic it runs when starting a fade). IIRC it actually did originally have the property named "Active", and someone reported that as inconsistent with other behaviors, so we renamed it to "enabled", and I don't think it's worth reversing that. Also renaming core features that have been in use for many years causes problems with making tutorials, manual entries, lesson plans etc. go out of date and need updating, so I generally avoid that wherever possible.
> 
> TBH the Fade behavior is pretty much made redundant by the Tween behavior, as a fade is just a special case of an opacity tween. So I'd rather not touch the Fade behavior, and I'd probably deprecate it if it wouldn't cause such a problem with things like tutorials as I mentioned.

@AshleyScirra Could you write a list of what not to touch? Like for example the behavior of `Pin` and use a hierarchy instead? I think it would be very useful to know the full list.

**Comment by AshleyScirra** [comment]
I added a manual guide on [superseded features](https://www.construct.net/en/make-games/manuals/construct-3/tips-and-guides/superseded-features).

**Comment by WilsonPercival** [comment]
> I added a manual guide on [superseded features](https://www.construct.net/en/make-games/manuals/construct-3/tips-and-guides/superseded-features).

@AshleyScirra Thanks a lot!

**Comment by dop2000** [comment]
> So I'd rather not touch the Fade behavior, and I'd probably deprecate it if it wouldn't cause such a problem with things like tutorials as I mentioned.

No, please don't do it! In many cases Fade is more convenient and easier to use than Tween. You can configure all three stages in one Fade without any code - fade in, wait, fade out. With Tween this will require several unnecessary events.
