### ISSUE TITLE
MoveTo Cannot Skip over multiple waypoints over a single frame

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-bugs#7307]
## Problem description

The Moveto behavior slows down noticeably when given a lot of very close waypoints

## Attach a .c3p

[moveToWaypoint.zip](https://github.com/Scirra/Construct-bugs/files/12345043/moveToWaypoint.zip)

## Steps to reproduce

1. Press preview
2.
3.

## Observed result

![image](https://github.com/Scirra/Construct-bugs/assets/11213825/0615ac29-f2bd-428a-aff0-fe00c02d0e2c)
The more there are waypoints, the slower it is

## Expected result

They should all have the exact same speed

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Well, it's not designed to be used like that. It doesn't seem a realistic use of the behavior. Do you really need this?

**Comment by skymen** [comment]
I am using it for a snake-style movement for two different games (BioGun and the game by Tokinsom)

Here is how it looks when it's all working fine:

https://github.com/Scirra/Construct-bugs/assets/11213825/e0857832-bae0-4e7d-b179-237344296074

However, this only works because I have all elements of the snake follow the same timeline at the same time and then regulate the moveTo speed.

The issue is what happens when the head is not also using moveTo and instead uses another behavior like Bullet or Sine:

https://github.com/Scirra/Construct-bugs/assets/11213825/6da4da24-4d42-4c4f-a083-70c76194aa6a

In this case, other methods have a noticeable "body detaching" style that might not fit every game and my solution would work, granted the waypoints system worked the way I thought it did. Because then I need to constantly add new waypoints every tick or every X seconds and then do my speed regulation thing

Here is what happens in this case:

https://github.com/Scirra/Construct-bugs/assets/11213825/8897b222-eb58-42cf-807f-1898fc3380ef

Now, I understand this might be a lot of work and most importantly I know that for backwards compatibility reasons, it's not reasonable to just replace the old behavior with the new one, and that you need to keep a way to toggle between both.

I have debated making my own addon that does exactly this for a long while now, so maybe it would be better if I just wrote something new entirely.

**Comment by AshleyScirra** [comment]
If the body parts behind the head are following exactly the same path as the head, then wouldn't it make sense to have logic that just follows the head, rather than trying to use 'Move to' like this?

**Comment by skymen** [comment]
Pin Chain cuts corners. I'm not trying to have each object roughly follow its parent, I want each object to follow the same exact path the parent took. I don't see how I can do this without something vaguely akin to the waypoint system (aka storing position and following them later)

**Comment by avishaymizrav** [comment]
> Pin Chain cuts corners. I'm not trying to have each object roughly follow its parent, I want each object to follow the same exact path the parent took. I don't see how I can do this without something vaguely akin to the waypoint system (aka storing position and following them later)

I'm doing something similar in my game:
![wormZombieCode](https://github.com/Scirra/Construct-bugs/assets/4296822/621e92c1-b4a8-4568-99ac-6cb04ce1139a)

The head and other body parts are all in the zombieWorm family.

**Comment by AshleyScirra** [comment]
So you want "follow exact path of parent but at fixed distance behind rather than fixed time behind"?

I think even if we fixed the Move To behavior to work like you want it to, then it still won't achieve that. It has its own speed and acceleration control per instance, and so it wouldn't match the speed of the head, it would catch up or fall behind as it is just following a series of waypoints, not trying to match the distance to the object ahead. So it seems like the wrong feature to use for that.

Even regardless of that, I don't really think this is an appropriate use of the Move To behavior; its waypoints are meant to be used as a series of separate destinations a reasonable time and distance apart, and not to be used as a movement history. I think supporting that probably does amount to a special behavior. What it sounds like you want is a feature that tracks the position history of the head, and then advances through the history to maintain a fixed distance to the object ahead, based on measuring the length of the path remaining. Move To definitely doesn't do that. So I don't think this is something we should change in Move To.

**Comment by WilsonPercival** [comment]
> Pin Chain cuts corners. I'm not trying to have each object roughly follow its parent, I want each object to follow the same exact path the parent took. I don't see how I can do this without something vaguely akin to the waypoint system (aka storing position and following them later)

@skymen Look, I did, does it suit you?

[path_advanced.zip](https://github.com/Scirra/Construct-bugs/files/12346709/path_advanced.zip)

**Comment by skymen** [comment]
Yes @WilsonPercival it's roughly what I'm trying to do, thanks. Alright, I think i'm just gonna write my own behavior then.
