### ISSUE TITLE
Phone keyboard height issue

### ISSUE THREAD

**Issue by DeividHiGamboa** [Scirra/Construct-bugs#7351]
## Problem description

Hello, since my previous post was closed, so I decided to try to make the game know the height of the keyboard, and I succeeded, the problem is that it only works in the browser and not in the apk, in the apk it returns 0px and in the browser it returns the height of the keyboard, to explain virtual keyboard api has css variables and i decided to use this, this is the variable: "keyboard-inset-height"

Is there a cordova lock on this variable so that it only returns 0px? Why does it work in the browser and not in the apk? 

Browser:

https://github.com/Scirra/Construct-bugs/assets/109392555/84d5d88a-b82a-46d2-82a0-ba5b8b5858b0

Apk:

https://github.com/Scirra/Construct-bugs/assets/109392555/91790abc-e1bb-4c18-ba07-ece3d8fd3e38

## Attach a .c3p
[VirtualkeyboardHeight.zip](https://github.com/Scirra/Construct-bugs/files/12478785/VirtualkeyboardHeight.zip)

## Steps to reproduce

1.open my example
2.Run a remote preview and test on an android phone, and see how it returns the keyboard height
3.Then export in apk and see how it only stays at 0px and does not return the height of the keyboard

## Observed result
That in apk does not return the height of the keyboard

## Expected result
That both in the browser and in the apk return the height of the keyboard

## More details

**Affected browsers/platforms:** 
Android and maybe ios

**First affected release:** 
Since ever 
## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
The problem here is you are trying to use part of the Virtual Keyboard API (the `keyboard-inset-height` CSS variable), but that is not supported by the Android WebView which is what Android apps are loaded in. There is an [issue filed with Google about that here](https://bugs.chromium.org/p/chromium/issues/detail?id=1259101), which Google will need to fix for this to work.

The existing virtual keyboard behavior in Android apps is something we've hacked in to work around the limitation to try to make it work like it does in the Chrome browser, but that does not use the Virtual Keyboard API and so things like its associated CSS variables won't work.
