### ISSUE TITLE
Variable Platform Behavior vector y jump height

### ISSUE THREAD

**Issue by VertexZero** [Scirra/Construct-bugs#7359]
## Problem description

When using the Platform Behavior and attempting to Jump by setting the Player vector Y value to -Jump Strength, there's an inconsistency in the jump height when compared to using Simulate Control Jump

## Attach a .c3p
[https://drive.google.com/file/d/1UFaOPdLm9B0aHz_u1ENqWo2Nkh4hyOIJ/view?usp=sharing](url)

## Steps to reproduce

1. In the provided project, set press Up Arrow key to Jump. 
2. Set _canSimulateJump_ to '0' in order to test with 'Simulate Platform pressing Jump'

## Observed result
In both cases, there's a small difference in the jump height.

## Expected result

In both cases, it should give the same result.

## More details

A method suggested by Discord user Federico Calchera seems to fix it.
The method is commented in the project file provided.

<details><summary>View details</summary>

</details>

**Comment by AshleyScirra** [comment]
It's currently by design. Jumping is handled specially to preserve framerate independence (#6550). Setting the vector has no special handling because the Platform behavior doesn't know what you're trying to do. So if you mean for the player to jump, simulate a jump; if you just want to arbitrarily control the player movement then you can control the vector with the vector actions, but they won't be treated exactly the same as a jump.

**Comment by VertexZero** [comment]
Thanks for the clarification.
