### ISSUE TITLE
HTML5 browser Game won't play on Itch.io in Firefox when exported with Advanced Minify.

### ISSUE THREAD

**Issue by ShibeyFaceGames** [Scirra/Construct-bugs#7402]
## Problem description

When exporting games to HTML5 for Itch.io, many of my games will no longer run in Firefox if Advanced Minify is turned on. It will just sit on a blank, black screen. This started with r358. They will run if exported from the previous stable build (r350) or if I use "simple minify" in r358. I only tested two other browsers, Edge and Chrome, both on Windows 10, and they do not seem to have this issue.

## Attach a .c3p

(https://www.dropbox.com/scl/fi/636w13qqxk62tglldtek0/ACC_Cutdown_FAILS.c3p?rlkey=z32xb36iujox108tdlwkfgowt&dl=0)

## Steps to reproduce

1. Inside the group "Mainloop" --> Subgroup "EnemyLogic" I've narrowed it down to 4 Subgroups that seem to cause the bug.
2. Enabling "BossSeals", "EndBoss", "EnemiesDie", or "WobbleEnemy" causes the crash. Disabling or deleting them should allow the game to run.
3. This is a HEAVILY cut-down file with no actually game left, just a start menu, but the freeze still occurs if these 4 subgroups are active.

## Observed result

If any of the 4 subgroups mentioned above are active, the game will not start in Firefox. It won't even reach the loader icon/bar, it just sits on a black screen. I'm not entirely sure the cause, especially since they run fine in "simple" mode or in Edge and Chrome, and I don't think the logic/events in those groups are wildly different from the others.

## Expected result

I expected the game to run, as it did in r350 and in other browsers.

## More details

Seems to be Firefox specific. Firefox is up to date. I'm running Windows 10 Pro 22H2 build 19045.3448  Did not occur with NW.JS windows build either. Also, the example I included is a cut-down version of one game, but it's not the first game I had the problem with... it was just the easiest to isolate the code blocks that were causing the bug. I have another game built entirely separately that has the same issue.

**Affected browsers/platforms:** Firefox 117.0.1 (64-bit)

**First affected release:** Worked in r350, bug started r358

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r358 (stable)
Browser: Chrome 116.0.5845.188
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 285 gb
Storage usage (approx): 713 mb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA Quadro P4000 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8) -->

</details>

**Comment by WilsonPercival** [comment]
I can reproduce the problem in Mozilla. Everything works fine in Chrome. This is not related to itch.io, I can also repeat the problem on netlify.

I did some work to remove the unwanted parts. But soon I came to the conclusion that by deleting any element the problem disappeared. So, for example, if in event 208 in the function call action we pass `0` in the second argument instead of `random(50, 100)`, then the error is no longer observed.

I'll leave a simpler version of the project here in case it helps to find the cause of the error faster.

<img width="960" alt="observed" src="https://github.com/Scirra/Construct-bugs/assets/91274932/cfb806c4-14dc-4406-aa96-888925e87b35">

[bug_new_project.zip](https://github.com/Scirra/Construct-bugs/files/12656925/bug_new_project.zip)

**Comment by AshleyScirra** [comment]
I can't reproduce this - I exported it with r359 and advanced minification, and it runs fine for me in Firefox on a local web server. I tried uploading it to Netlify Drop and it seems to work fine there in Firefox as well: https://venerable-kangaroo-5e4686.netlify.app/

If the problem was with Construct, Closure Compiler, or Firefox, this should have reproduced the issue. So I suspect the problem is with the host: perhaps itch.io, and perhaps Netlify as well, run some custom JavaScript code on the page which is interfering with minified code. I think we've had this kind of problem before: if some other script runs which exposes short global variable names like `a` and `b`, these can end up conflicting with minified JavaScript code, which tends to rename longer variables to short names like `a` and `b` as well. Carefully-written JavaScript code should not accidentally expose any global variables and so remain compatible with minified JavaScript code, but when using classic mode scripts, or especially "sloppy" (non-strict) mode scripts, it's much easier to accidentally create global variables, as things like merely forgetting to declare a variable can create an accidental global variable.

However all that is out of our control. I think you'll need to report these issues to itch.io and Netlify if also affected, as they'll need to update any additional scripts to be compatible, if that's the problem. But as it stands a normal advanced minify web export with the provided project works fine for me in Firefox, so I don't see that Construct is generating any invalid code.

**Comment by WilsonPercival** [comment]
> I can't reproduce this - I exported it with r359 and advanced minification, and it runs fine for me in Firefox on a local web server. I tried uploading it to Netlify Drop and it seems to work fine there in Firefox as well: https://venerable-kangaroo-5e4686.netlify.app/
> 
> If the problem was with Construct, Closure Compiler, or Firefox, this should have reproduced the issue. So I suspect the problem is with the host: perhaps itch.io, and perhaps Netlify as well, run some custom JavaScript code on the page which is interfering with minified code. I think we've had this kind of problem before: if some other script runs which exposes short global variable names like `a` and `b`, these can end up conflicting with minified JavaScript code, which tends to rename longer variables to short names like `a` and `b` as well. Carefully-written JavaScript code should not accidentally expose any global variables and so remain compatible with minified JavaScript code, but when using classic mode scripts, or especially "sloppy" (non-strict) mode scripts, it's much easier to accidentally create global variables, as things like merely forgetting to declare a variable can create an accidental global variable.
> 
> However all that is out of our control. I think you'll need to report these issues to itch.io and Netlify if also affected, as they'll need to update any additional scripts to be compatible, if that's the problem. But as it stands a normal advanced minify web export with the provided project works fine for me in Firefox, so I don't see that Construct is generating any invalid code.

@AshleyScirra I just ran it on a local server and got the same error. Could you provide me with the exported archive so that I can compare it with mine and find differences if there are any? This is an assumption in case minification occurs differently on different computers.

<img width="960" alt="obser" src="https://github.com/Scirra/Construct-bugs/assets/91274932/283e79a2-3cfc-4707-a756-ad7b85c4cc4e">

**Comment by WilsonPercival** [comment]
@AshleyScirra @ShibeyFaceGames Strange, I can't repeat the mistake again. Either it was just fixed or it's a floating bug...

**Comment by ShibeyFaceGames** [comment]
@AshleyScirra @WilsonPercival Thanks for all your help! Not sure if this is useful information at this point, but I still have this issue with R358. However, I loaded the 359 beta and it works fine, so I assume it'll be fixed going forward!

Asking as mostly a hobbyist, do you think I should keep working in the beta version? Or stick to the stable R358 for work, and export from R359+ until the next stable is released? Thanks again!

**Comment by WilsonPercival** [comment]
> @AshleyScirra @WilsonPercival Thanks for all your help! Not sure if this is useful information at this point, but I still have this issue with R358. However, I loaded the 359 beta and it works fine, so I assume it'll be fixed going forward!
> 
> Asking as mostly a hobbyist, do you think I should keep working in the beta version? Or stick to the stable R358 for work, and export from R359+ until the next stable is released? Thanks again!

@ShibeyFaceGames Usually everyone tries to stick to a stable version so that the chance of damaging the project is minimal. But if you want to help catch more bugs, you can use the beta version.

**Comment by ShibeyFaceGames** [comment]
That's more or less what I figured. Seems that if I want to kick out HTML5 builds of my current project, I may need to export from the beta for now. But I'll keep the main working file in R358. Thanks again for your help!

**Comment by AshleyScirra** [comment]
A while after looking in to this, I realized it's a possible issue to do with advanced minify renaming global variables so they accidentally clash in the DOM and worker scripts. That means it's not actually Firefox-specific, it's to do with running in DOM mode rather than worker mode, as Firefox doesn't currently support worker mode.

It's difficult to reproduce this but I have a fix in for the next beta, so I think that should prevent it happening again.
