### ISSUE TITLE
super minor issue, Epic Games icon white fill

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#7411]
## Problem description
the icon of the Epic Game (WebView2) plugin has the interior lettering filled with white instead of being transparent.

![image](https://github.com/Scirra/Construct-bugs/assets/89512047/92dcba2b-d360-475c-b618-bf50abc8c818)

**Comment by AshleyScirra** [comment]
I don't actually know how to fix this. I got a stock SVG icon for Epic Games, and it draws white text over the background. If you make the text transparent then it just draws the solid shape behind it rather than cutting out the text. I don't know enough about SVG/masking to figure out how to get the text to do a cut-out (i.e. destination-out compositing mode) or to rewrite the path to go around the text. If you can figure out how to do it, feel free to submit a PR!
