### ISSUE TITLE
Set position not working with tile movement

### ISSUE THREAD

**Issue by loritsi** [Scirra/Construct-bugs#7426]
## Problem description

When applying the 'Tile Movement' behavior to a Sprite and place into the layout at position A in the editor and then assigning an "on layout start set position to position B", the sprite will correctly set itself at position B but then glide back to position A.

## Attach a .c3p

It would not let me attach one directly so here is a link
https://easyupload.io/yds2hd

## Steps to reproduce

1. Place a sprite on the layout with the tile movement behaviour.
2. On the event sheet, give the sprite the following instruction:
```
+ System: On start of layout
-> Sprite: Set position to (200, 200)
```
3. Preview the layout.

## Observed result

The sprite starts at the set position and then glides back to its initial position in the editor.

## Expected result

The sprite should start at the set position and stay there.

## More details

**Affected browsers/platforms:** 

Firefox and Chrome, others untested.

**First affected release:** 

It has been an issue since at least 2019, according to another user on the forum.

## System details

<details><summary>View details</summary>

Product: Construct 3 r360 (beta)
Browser: Firefox 117.0
Browser engine: Gecko
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/117.0
Language setting: en-US
Local storage

Storage quota (approx): 931 gb
Storage usage (approx): 612 mb (0.1%)
Persistant storage: Yes
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to [bug 1163426](https://bugzilla.mozilla.org/show_bug.cgi?id=1163426)
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    Determining input device capabilities is not supported.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 980 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_bptc
    EXT_texture_compression_rgtc
    EXT_texture_filter_anisotropic
    OES_draw_buffers_indexed
    OES_texture_float_linear
    OVR_multiview2
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context
    WEBGL_provoking_vertex

Audio information

System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)
    WebM Vorbis (audio/webm; codecs=vorbis)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm; codecs=av01.0.00M.08)
    MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This might seem strange but it is actually by design. The problem is with movement behaviors like Tile movement, if something unexpectedly changes its position, it doesn't know why. If every time it sees its position change, it decides it's just now sitting in that cell, then things like being slightly nudged by an obstacle while moving in to a cell cause it to just stop or go somewhere else, which is sometimes an unwanted result. There are lots of tricky cases involving this kind of thing (e.g. #4866, #5817, #6616). Instead the Tile movement uses an algorithm where it has a target grid cell it's trying to get to, and it always tries to keep moving in to that cell, even if something repositions it, so it can handle things like being unexpectedly bumped during movement.

If you want to deliberately put the object somewhere else, use the Tile movement *Set grid position* action with *instant* mode. Using the behavior's own action makes it explicit you intend to reposition the object, rather than relying on unexpectedly changing its position by other means, which is in fact an inherently ambiguous thing for the behavior to try to respond to (and so it's probably impossible for it to always figure out the right thing to do).
