### ISSUE TITLE
Alpha clamp incorrect rendering in WebGL

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-bugs#7446]
## Problem description

The `Alpha clamp` effect displays differently in `WebGL` and `WebGPU`.

## Attach a .c3p

[alpha_clamp_particles_web_gpu_bug_r361b.zip](https://github.com/WilsonPercival/WilsonPercival/files/12837573/alpha_clamp_particles_web_gpu_bug_r361b.zip)

## Steps to reproduce

1. Open a project.
2. Open remote preview.
3. Copy the link and open in a new window. Move the window to the left half.
4. Return to the editor and change the value of the `Enable WebGPU` parameter to `Yes` in the left ear.
5. Click `Preview`.
6. Copy the link and open in a new window. Move the window to the right half.

## Observed result

https://github.com/WilsonPercival/WilsonPercival/assets/91274932/fb22861c-2f53-4e74-b80d-0b7fb114c2e7

## Expected result

The `Alpha clamp` effect displays the same in `WebGL` and `WebGPU`.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** broke in r361b

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r361 (beta)
Browser: Chrome 117.0.5938.132
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 283 gb
Storage usage (approx): 226 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Issue #7396 shows that particles are not rendering correctly in WebGPU and this appears to be just another variant of that, so merging.

**Comment by AshleyScirra** [comment]
Minimal repro: [issue7446.zip](https://github.com/Scirra/Construct-bugs/files/13167969/issue7446.zip)

It's nothing specific to particles, it reproduces with a simple sprite.

**Comment by AshleyScirra** [comment]
This is a pretty confusing situation, but it turns out that actually the WebGPU effect is correct. The 'Alpha clamp' effect in WebGL is the broken one - it does not properly handle premultiplied alpha. In this case as the image is all white pixels but fades out the alpha, then clamping the alpha to 100% should mean it appears solid white; however the bug in the existing 'Alpha clamp' effect means it incorrectly darkens towards the edges.

This presents a difficult backwards compatibility problem: it is not actually doing a proper 'Alpha clamp' effect, but it's been broken for many years and so many projects probably use the effect anyway and rely on its current appearance. So what I've done for the next release is:

- Rename the existing (broken) 'Alpha clamp' effect to 'Alpha threshold', and aligned the WebGPU shader to match the WebGL appearance (with darkening towards the edges)
- Added a new effect named 'Alpha clamp', which implements the correct effect; both WebGL and WebGPU render this effect consistently (keeping solid white in this example)

This means new uses of the 'Alpha clamp' effect implement the correct effect, but existing projects (or anyone who liked the old appearance despite it being technically incorrect) can keep using the 'Alpha threshold' effect.
