### ISSUE TITLE
Possible JSON 0 index bug

### ISSUE THREAD

**Issue by q3olegka** [Scirra/Construct-bugs#7498]
## Problem description

The key from the 0 index of the array is saved after it is deleted

[json-bug.zip](https://github.com/Scirra/Construct-bugs/files/13191681/json-bug.zip)

## Steps to reproduce

Run the source and open the console in the browser

Create multiple keys in an array.
Try to get the value from the 0 index of the array, via JSON.Get.
Delete 0 index of the array.
Try again to get the value from the 0 index.
The value will be equal to the deleted one

## Observed result

the parameter id 0 of the array index is always 3

## Expected result

id = 3
id = 2
id = 1

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Minimal repro: [issue7498.zip](https://github.com/Scirra/Construct-bugs/files/13204286/issue7498.zip)

**Comment by AshleyScirra** [comment]
Wait, the actual repro uses "Pop front". Second minimal repro: [issue7498-b.zip](https://github.com/Scirra/Construct-bugs/files/13204403/issue7498-b.zip)

(Please always try to file the most minimal repro you can as per the bug report guidelines, otherwise I have to reduce it myself and it can be tricky!)

**Comment by AshleyScirra** [comment]
Fixed for next beta.

Note: the 'Delete key' action does not delete array indices by design. (I added a note to the manual entry to clarify this.) This initially tripped me up because the steps to reproduce mention "delete" and is what issue7498.zip uses. However the issue only occurs with the array manipulation actions like "pop front", which is what issue7498-b.zip uses.
