### ISSUE TITLE
Spritefont wrapping word incorrect

### ISSUE THREAD

**Issue by TecenGOD** [Scirra/Construct-bugs#7507]
## Problem description

The text in Spritefont does not transfer words to a new line, but goes beyond the boundaries of its object.

## Attach a .c3p

[spriteFont bug.zip](https://github.com/Scirra/Construct-bugs/files/13197911/spriteFont.bug.zip)

## Steps to reproduce

1. Open project

## Observed result

![image](https://github.com/Scirra/Construct-bugs/assets/7480088/226f34b4-4aee-46d5-ad4e-852eaa89f84a)

## Expected result

![image](https://github.com/Scirra/Construct-bugs/assets/7480088/f52fefb8-4861-4e9f-b606-953af3190fc4)

## More details
The error is observed on R358, as well as on beta R364

**Comment by AshleyScirra** [comment]
Minimal repro for debuggability: [issue7507.zip](https://github.com/Scirra/Construct-bugs/files/13204743/issue7507.zip)

**Comment by AshleyScirra** [comment]
It looks like this only happens because you have a really weird sprite font image. The characters themselves are only about 5x7px, but the image has a 54x54 box for each character, and the character doesn't even appear to be in any particular alignment inside that box:

![image](https://github.com/Scirra/Construct-bugs/assets/768723/b695f203-9fad-4249-bb85-bd88cb1d1fe9)

This has other weird effects for text layout - for example if you left-align the text, it doesn't actually align to the left edge of the box, because there is ~23px of transparent space to the left of a 5px wide character, and it thinks that's part of the character image, so it's including it. So that's not really a bug, even though it looks wrong - the problem is the arrangement of the spritefont image.

I think in this case the text going off the right of the box is a similar case - the text layout engine expects a reasonably arranged spritefont image, but there's so much free space that it is messing with the drawing and layout calculations, in a way I don't think we can or should reasonably fix. The problem is the spritefont image, so you should fix that instead. The box for a character should just about fit the largest character, and then use the spacing settings to trim down smaller letters; don't use them to try to crop a much larger box, as it's not designed for that.

**Comment by TecenGOD** [comment]
@AshleyScirra, I use Spacing Data so that each character has its own width. The engine doesn't take this into account, so it's a bug.

**Comment by TecenGOD** [comment]
@AshleyScirra, I have reduced the size of the character to 24 pixels (this is the minimum I can afford), and at the same time the text still goes beyond its boundaries and does not transfer the word to a new line. That is, changing the size of the symbol cell did not change anything.
[spriteFont bug2.zip](https://github.com/Scirra/Construct-bugs/files/13205125/spriteFont.bug2.zip)

**Comment by brushfe** [comment]
<img width="295" alt="image" src="https://github.com/Scirra/Construct-bugs/assets/63005234/23b46f6d-171d-488d-8085-75c318b6051e">

<img width="705" alt="image" src="https://github.com/Scirra/Construct-bugs/assets/63005234/febe8c83-a0f8-4706-a2a7-b03533648546">

If you take the advice above, and left align your characters inside their spritefont boundaries, it looks closer to your goal. I think Spacing Data only adjusts the space after (to the right) of a character, so centered characters in a spritefont don't work well.

**Comment by TecenGOD** [comment]
@brushfe, Well, if we shift the characters to the left, then it looks good for sentences. But the words are no longer centered normally... 
@AshleyScirra, it still looks like a bug.
![image](https://github.com/Scirra/Construct-bugs/assets/7480088/798a34c6-eaa5-4327-a978-ed3ec92a8d67)

**Comment by AshleyScirra** [comment]
Just use a normal spritefont image. The engine doesn't support massive spacing between characters like this, and most likely won't, because there doesn't seem to be any reason for it, and it would add a lot of complexity to the code. I do not recall anyone else ever doing this with the SpriteFont object in all the years it has been around.
