### ISSUE TITLE
effects sdk: wgsl depth sampling parity issue

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#7559]
## Problem description

I have created a 3rd party shader that relies on sampling pixels at an offset, for proper blending I also need to sample the depth of those pixels.
In GLSL I can sample the depth at the same coordinates as the front, i.e. `vTex + 1. * pixelSize`, but when I try to port this shader over to WGSL I struggled to find a way to get a similar logic to work, the issue is that sampling the front works with input.fragUV while sampling the depth texture is done with `c3_getDepthUV(input.fragPos.xy, textureDepth)` in WGSL.

Maybe there is a way to get something similar to work with some additional math, but I tried and asked around but I sadly didn't find a solution. So I opened this as a bug as this seems to be a parity issue from webGL to webGPU, that would make it difficult to move some projects over to webGPU.

(this also affects other shaders like Mikals popular SSAO and another shader I am working on that creates outlines based on depth)

## Attach a .c3p

example project with the 3rd party shader bundled (webGL 1+2 works, WGSL doesn't):
[dofShaderExample.zip](https://github.com/Scirra/Construct-bugs/files/13420216/dofShaderExample.zip)

the .c3addon as zip of the shader
[dofEffect.zip](https://github.com/Scirra/Construct-bugs/files/13420192/dofEffect.zip)

## Steps to reproduce

1. try creating a shader that samples front and depth at the same position, but at an offset from the current fragment

## Observed result
I didn't find a way to do it in WGSL

## Expected result
It can be done in WGSL

## More details
I'm sorry if I am just missing something and there is an easy way to do it. But I would really appreciate some help on this!

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by F3der1co** [comment]
I just had the same issue with another shader where I sample the background at an offset. I realized that you must have had the same issue in your water background shader. There you seem to use textureSampleGrad() and some additional calculations to get ddx and ddy. Really goes over my head but at least that seems like a solution.
I really wish we could get a helper function for this though!

**Comment by AshleyScirra** [comment]
This issue amounts to asking me to debug a complicated third-party shader, and debugging shaders is extremely difficult, not least because there is no ability to attach a traditional debugger. In this case producing a minimal repro is especially important. Can you provide a minimal example that uses the simplest possible shader? Ideally it would just do something like output solid colors and have an obvious difference between WebGL and WebGPU.

**Comment by AshleyScirra** [comment]
Coming back to some WebGPU issues, and as of the latest releases, the depth sampling should be consistent between WebGL and WebGPU. (It was buggy a few months back, but it was since fixed.) Here is a test project which demonstrates that: [ZDepthTest.zip](https://github.com/Scirra/Construct-bugs/files/14183575/ZDepthTest.zip)

With both WebGL and WebGPU, the Fogexponential effect renders the same, showing a green fog color about halfway up the very tall 3D shape, which stretches from Z -1000 to 0. The fog calculation does exactly the same maths between the GLSL and WGSL shaders - there is no difference to the handling of depth values in WGSL (although some of the details differ, such as providing utility functions for common calculations).

I think this is probably just a mistake in the shader code, but it's difficult to diagnose and we are not normally responsible for third-party code. To be able to investigate there would need to be the most minimal shader possible, as per the bug report guidelines, and especially important with shaders as there is nothing equivalent to browser dev tools for shaders. However the test project I provided appears to show depth sampling working equivalently between WebGL and WebGPU so there does not appear to be a bug with that, so I'm closing this issue on the assumption it's a mistake in the WGSL shader code.

FWIW WGSL does not provide a `pixelSize` shader uniform, because it's redundant: you can get the same value, for any texture, by using the `textureDimensions` builtin. The C3-provided utility function `c3_getPixelSize` calculates `vec2<f32>(1.0) / vec2<f32>(textureDimensions(texture))` which illustrates how to get the pixel size (which in that case is for texture_2d, but the same principle applies to the depth texture). So if something is off with the handling of pixelSize, it probably means getting that part right.

**Comment by F3der1co** [comment]
looking at it again, it seems like I made some really dumb mistakes in the WGSL variant and with the additional information you gave I think I got it working almost identical now. Thank you!
