### ISSUE TITLE
Changing audio action with "back" puts values in the wrong text fields

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-bugs#7586]
## Problem description

Sometimes I change my mind on what type of audio action I want to use, and so I click the "Back" button, but this then rearranges the default values of the fields. 

I think this affects all the audio "Play" actions.

It can get a bit messy! Since I don't expect the values to be changing, I didn't even realize it's been happening. 

Here's an illustration to make it clearer:

________

## Making a 'play at position' action

![image](https://github.com/Scirra/Construct-bugs/assets/5744908/963e5ffc-9b5b-489a-b1eb-88a447af7f28)

## Change my mind and click "back" and select 'play at object'

![image](https://github.com/Scirra/Construct-bugs/assets/5744908/35add1c7-663c-43fd-83e4-3d30f0829526)

Notice how it shows "sprite.Y" in the angle section?

## Compare this to a "fresh" play at object action:

![image](https://github.com/Scirra/Construct-bugs/assets/5744908/aa8055fd-9396-4018-b567-a5d6e26f71a4)

The angle text fields have all changed, even though all I did was click back and change to a new action.

___________

## Attach a .c3p

[audioBug.zip](https://github.com/Scirra/Construct-bugs/files/13496760/audioBug.zip)

## Steps to reproduce

1. Change the play at object, or play at position action, to a different play action

## Observed result

The values are all in the incorrect places

## Expected result

The values should be staying consistent.

Or have values be like a fresh action (where you haven't clicked "back" yet). 

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is currently by design, and I'm not sure there's a better way to do it.

It is simply restoring the entered parameters by their index. So for example whatever you typed for the 2nd parameter will be preserved (if possible) if you go back and choose something else. Of course that is not always appropriate when choosing something with completely different parameters. But it is more often than not a useful thing to do, such as entering a string for "set text", pressing back, choosing "append text", and then it's remembered what you put.

I don't think the editor has a good way of doing anything smarter. It could try to remember things by something like the internal ID of the parameter, but then I think in the vast majority of cases it will fail to remember anything at all, and so the overall usability will be worse. If it tries to mix index and ID, then there are probably lots of confusing cases where some things are remembered by ID and others by index, it would probably end up a very complicated scheme, and then it will probably still put things in weird places sometimes.

I think the current design is OK in that it makes a best effort to remember what you typed. Sometimes that's not appropriate, but I think it's difficult to make any better, most of the time it's still useful, and assuming you review all the parameters before finishing then you have a chance to fix anything that was not appropriately auto-filled.
