### ISSUE TITLE
Physics.SetVelocity overrides object position

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-bugs#7589]
## Problem description
I am trying to make a Portals effect, where an object goes in with vx,vy velocities, teleports to the other portal, and preserves its vx,vy.
Problem is, when I set the new velocity after exiting the portal, it teleports back to the entrance portal.

## Attach a .c3p
[portal.zip](https://github.com/Scirra/Construct-bugs/files/13498679/portal.zip)

## Steps to reproduce

1. Set constant `Auto=false`.
2. Preview.
3. Click `Kick`.
4. Click `Teleport` when the object is at the Blue portal.
5. Back to editor
6. Set constant `Auto=true`.
7. Preview
8. Click `Kick`.

## Observed result
After 4.: object (manually) restores its velocities.
After 8: object teleports for a split second then goes back to the entrance position.

## Expected result
Step 8 should give the same result as 4, with automatic and smoother teleport.

## More details

**Affected browsers/platforms:** tested in Chrome

**First affected release:** current stable

**Comment by WilsonPercival** [comment]
@Alaadel This is how it works:

[solution.zip](https://github.com/Scirra/Construct-bugs/files/13499298/solution.zip)

**Comment by AshleyScirra** [comment]
I looked in to the original project and it does seem difficult to teleport a physics object preserving the velocity. The problem is if you use 'Set position', the Physics object tries to track the changes and control the velocity so the physics simulation responds more appropriately, such as if you control a Physics object by mouse. However this tracking does not work well with a one-off change in position, as it ends up applying two ticks of correction, which is tricky to override.

For the next beta I've added a 'Teleport' action which just sets the physics body position preserving its velocity, which makes this case much simpler - you can just use that one action and everything works fine.
