### ISSUE TITLE
IconSets Can not working in Family

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#7601]
## Problem description

Currently, IconSets cannot be use via [icon=Tag] even if the Family object is selected.I don't know if this is by design, but I think it should work, so file it as a bug. If this is not a bug, I will submit it as a suggestion.

![Snipaste_2023-12-01_16-22-17](https://github.com/Scirra/Construct-bugs/assets/45864744/9dbbfe2b-a66c-4c4b-bcb7-0a7972675256)

## Attach a .c3p

[iconsets-family.c3p.zip](https://github.com/Scirra/Construct-bugs/files/13522702/iconsets-family.c3p.zip)

## Steps to reproduce

1.
2.
3.

## Observed result

[icon=Tag] cannot work

## Expected result

[icon=Tag] can work

If this is by design, Family should be filtered when selecting iconset objects

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It's currently by design that the icon set can only refer to one object type. Supporting a family is essentially support for multiple object types with the members of that family. It's not clear how indexed icons would work in that case, nor is it clear what the use case for this is, as I always assumed a single icon set is sufficient. So this should be filed as a feature request instead.
