### ISSUE TITLE
Large Project Bottlenecks: Project View Search Time + Response

### ISSUE THREAD

**Issue by OneRepCloser** [Scirra/Construct-bugs#7612]
## Problem description

Large Project Series: A project with 18k objects (stress test)

The time it takes to search in the project view search bar takes a long time if a lot of objects pertain to the typed search.

The search responds too fast to the first typed character (relevant in large projects).

## Attach a .c3p

[Large_Project_Debug_0.zip](https://github.com/Scirra/Construct-bugs/files/13545911/Large_Project_Debug_0.zip)

## Steps to reproduce

1. Type "soda" in the search bar
2. Note how the search immediately responds to the character "s" (In a large project with several objects starting with s this is detrimental.)
3. Now type "soda" somewhere outside of the search bar copy it, and paste it into the search bar.
4. Note how a search bar that responds immediately to the first character typed in a large project can be detrimental.

Suggestion: Let the user configure some properties pertaining to the search bar functionality (time to respond to after typing, minimum characters before responding, etc).

**Comment by AshleyScirra** [comment]
Oops, didn't mean to merge this one, as it seems different.

**Comment by AshleyScirra** [comment]
I think we had similar issue with the Find Results Bar. We made that only update the search when you stop typing for a moment, rather than on the first character, for a similar reason (accidentally listing thousands of results for an incomplete search was slow). I think the same approach is relevant for the Project Bar with a large project, so I've updated the Project Bar search to use the same approach for the next beta. Marking as 'check next release' so we can get feedback on how it feels for your real-world project.

**Comment by AshleyScirra** [comment]
r371 is now out - @OneRepCloser, is it better with your real project?

**Comment by OneRepCloser** [comment]
@AshleyScirra 

Initial testing: 

Search bar changes seem to have been a clear improvement for my project and this functionality is now usuable for me (previously avoided the search bar), thank you.

**Comment by AshleyScirra** [comment]
OK, thanks for checking. Closing for now.
