### ISSUE TITLE
text bbcode outline rendering incorrectly

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#7649]
## Problem description
the bbcode outline seems to render on top of the text instead of below, this leads to the issue where the outline destroys the fonts shape and readability.

## Attach a .c3p
[bbcodeOutline.zip](https://github.com/Scirra/Construct-bugs/files/13672822/bbcodeOutline.zip)

## Steps to reproduce

1. look at project

## Observed result
![image](https://github.com/Scirra/Construct-bugs/assets/89512047/5c54dcc7-334f-4823-b34f-e837312ab694)

outline has artifacts, looks bad and is rendered on top into the letters.

## Expected result
outline is behind the text instead of in front (there are still some weird artifacts with the W, but just the render order would be a godsend)
![image](https://github.com/Scirra/Construct-bugs/assets/89512047/a212713e-44a6-4b71-88fb-8d4d77266d14)

## More details
I remember this was reported before and handwaved away, but maybe I misremembered as I didn't find a report.  
I think this is really a big issue as this make the outline unusable.  Alternative outline rendering via effects can be really performance intensive. So imo this just needs to be fixed.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>
Platform information
Product: Construct 3 r371 (beta)
Browser: Chrome 120.0.6099.71
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 0.8999999761581421
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 558 gb
Storage usage (approx): 1.9 gb (0.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 4070 (0x00002786) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
PASTE HERE

</details>

**Comment by XHXIAIEIN** [comment]
Is it possible to use rounded corners for edge? Similar to CSS style
```css
stroke-linejoin: round;
stroke-linecap: round;
```
This is an example of using SVG as text
https://codepen.io/RilDev/pen/vYeOjgj
https://codepen.io/shermanchens/pen/ZPBwyJ

**Comment by AshleyScirra** [comment]
This is difficult to change because doing what you suggest is a breaking change. If a Construct update changes to just put the outline behind the fill, then it essentially halves the outline width, which will change the appearance of all existing projects using outlines, and with thin outlines may cause the outline to become faint or disappear. If we double the outline width to compensate, it still changes the appearance, and in some cases the outline will then extend further than expected and so might get cut off, or cover up content it's not supposed to. It would also make it inconsistent with stroke text, which draws the outline only (and currently outline is just drawing stroke text on top of the filled text). I also think the current approach is fine so long as the outline is not too thick, so this seems to be a change mainly aimed at improving the appearance of text with a very thick outline.

Meanwhile you can work around this by having two text objects placed on top of each other, the bottom one using stroke text, and the top one using filled text.

I don't think this is a straightforward change as it would be a breaking change to improve a specific case of thick outlines which has a workaround. So I think this would be best dealt with as a feature suggestion - there'd probably need to be some special BBcode tag to handle this case so it's backwards compatible, but that is an enhancement, not a bug.

**Comment by brushfe** [comment]
"I also think the current approach is fine so long as the outline is not too thick, so this seems to be a change mainly aimed at improving the appearance of text with a very thick outline."

@AshleyScirra Personal aesthetic preferences can't be the reason to limit a feature though, can it? Isn't the point of creating an engine is to let users create whatever they prefer?

The bbcode outline feature is designed to make some text illegible, which has to be considered a bug (text has to be legible). 

Wouldn't fixing this be just like all the fixes to Platform we've seen? Users have been working around those for ages. But the fixes weren't considered a problem of backward compatibility, despite having to rework all our platform objects (to remove the workarounds).

**Comment by F3der1co** [comment]
To me this is a rendering bug as this clearly isn't an outer-line and there are even more issues depending on how the fonts vector was created: 
![image](https://github.com/Scirra/Construct-bugs/assets/89512047/bf3ee03f-85df-45b9-8ce3-bc635c1e832a)
here you can see that this font (Signika from Google Fonts) has overlapping vector shape that don't work with this render order.

I'll write it as a suggestion later.

**Comment by XHXIAIEIN** [comment]
Just as a solution supplement, I found that if use as SVG, can get a good stroke effect.
https://codepen.io/RilDev/pen/vYeOjgj
https://codepen.io/shermanchens/pen/ZPBwyJ

**Comment by F3der1co** [comment]
suggestion filed here: https://construct23.ideas.aha.io/ideas/C23-I-520
excerpt:
"For backwards compatibility I suggest these new bbcode tags:
- [outer-line] 2x and rendered behind
- [inner-line] 2x and source atop
- [center-line] like current outline"

**Comment by XHXIAIEIN** [comment]
> Meanwhile you can work around this by having two text objects placed on top of each other, the bottom one using stroke text, and the top one using filled text.

I tried to use this method to solve the problem, but quickly gave up! Because it would make the maintenance of the text particularly complex and terrifying. Every time when change the content, position, or size of the text, this means that need to update two texts at the same time. it's even more of a nightmare. If I remember correctly that placing too many text objects in the scene would also affect performance.
