### ISSUE TITLE
hierarchy arrows are drawn without anti-aliasing

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#7656]
## Problem description
Hierarchy arrows are drawn without anti-aliasing.
This might be a stretch as a bug report, so I am ready for a scolding. But they always looked bad/unprofessional and noisy to me. Now looking at the new Flowcharts system, there the links are beautifully smooth so I thought this is my chance as it seems like it's possible to do!
![image](https://github.com/Scirra/Construct-bugs/assets/89512047/9320cf7d-57df-4b6b-8a45-2f23093c2218)

## Attach a .c3p
[hierarchyArrows.zip](https://github.com/Scirra/Construct-bugs/files/13678533/hierarchyArrows.zip)

## Steps to reproduce

1. look at hierarchy links

## Observed result
jagged aliased lines, specifically distracting at some diagonal angles

## Expected result
smooth lines

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
I don't think this is worth it.

The reason the lines in flowcharts look good is because they are drawn using SVG elements so there really isn't any additional work for us to do in there.

The arrows in hierarchies on the other hand are drawn to the layout view using the same methods that are used to draw everything into any layout view. In order to make any improvement there, @AshleyScirra would need to write custom code that will only be used to draw slightly better angled lines, which would only be used in this specific case.

**Comment by F3der1co** [comment]
I see so it's not as easy as I thought. I can't judge how difficult it would be to add this custom rendering code but I think it would also improve other cases that aren't just these link, for example the rotated bounding boxes or the timelines cubic bezier curves:
![image](https://github.com/Scirra/Construct-bugs/assets/89512047/c3feb4e7-edbc-4f18-a37a-4cee3219f2f5)
![image](https://github.com/Scirra/Construct-bugs/assets/89512047/47cc3f6d-2590-4a49-b070-918d4f6334b5)

I'm aware that I care about this way more than the average user. But imo this is right on the edge where it's cosmetic but also usability related as these aliased lines look more messy than AA lines, leading to more visual clutter.

**Comment by AshleyScirra** [comment]
There is already a special "smooth line" renderer mode which hierarchy arrows could use. It does not use true antialiasing, but it uses a smoothing algorithm to achieve a similar result, which is used on rotated selection boxes. It only supports straight lines, but I think that could work with hierarchy arrows if it has a solid aliased fill but the outline drawn on top with smoothed straight lines. I'm not sure if it could handle bezier curves in the timeline as well, but it might if those are drawn as a series of short straight lines, so it might be worth experimenting with. Assigning back to @DiegoScirra !

**Comment by DiegoScirra** [comment]
From trying this out, it looks like you can have slightly better results for lines when they have a thickness of 3 pixels or more. At 1 pixel or 2 there doesn't seem to be too much of an improvement, specially if the line is drawn by itself, you still get the jagged edges.

Rotated selections already do this and it kinda works because they have a background of a similar colour to smooth out the line a little bit more. Timeline lines don't have a "natural" UI for the background and making the lines 3 pixels doesn't look too good to me.

The arrows of hierarchies can be improved a little bit, because they are already chunky, so making them a little bit chunkier doesn't change things much.
