### ISSUE TITLE
Platform falls through Jumpthru platforms

### ISSUE THREAD

**Issue by avishaymizrav** [Scirra/Construct-bugs#7687]
## Problem description

Platform falls through Jumpthru platforms.

## Attach a .c3p

[JumpthruBug.zip](https://github.com/Scirra/Construct-bugs/files/13721221/JumpthruBug.zip)

## Steps to reproduce

1. Try walking right and see what happens.

## Observed result

Platform falls through the platform.

## Expected result

Platform falls only when fall through action is triggered.

## More details
It seems like it doesn't fall through in the latest stable, but there is a visible glitch where the sprite jitters when going over the edges.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by WilsonPercival** [comment]
Maybe this: https://github.com/Scirra/Construct-bugs/issues/7361

**Comment by AshleyScirra** [comment]
Looks like a regression in r370. Probably was caused by #7361.

**Comment by AshleyScirra** [comment]
This actually looks like a mistake in the project. The *playerPH* object which has the Platform behavior does not have a flat base to its collision polygon: the bottom-left point is at Y=31.9, and if you move it down to Y=32 to match the bottom-right point for a flat line, then the issue no longer occurs.

I believe what is happening is since the base of the player's collision polygon is slightly sloped, it is actually moving vertically down the solid platform as it approaches the jumpthru bridge; as it has moved down, it is then overlapping the jumpthru by the time it moves off the solid. Previously Construct would move the player up through the jumpthru even though it was intersecting it, but this was janky, and caused the bug in #7361. Now that has been fixed the mistake in the collision polygon causes it to ignore the jumpthru to avoid the bug, and thus it falls through it (which is also the correct thing to do once a Platform object intersects a jumpthru).

Therefore it appears this project has a mistake in the collision polygon which caused unintended consequences, and those consequences were altered by a bug fix. Make sure your collision polygon is correct for Platform behavior objects as it's important to have it flat!

**Comment by avishaymizrav** [comment]
Oh wow, I setup that player sprite way back when I started the project 4 years ago, I'm pretty sure I set bounding box and only moved the top points, I have no idea how that happened :)

Thank you!
