### ISSUE TITLE
Webview 2 export does not work on Mac os

### ISSUE THREAD

**Issue by san40511** [Scirra/Construct-bugs#7693]
## Problem description

Webview 2 projects do not work if they were built on macOS

## Attach a .c3p

I tested it on 2 different mac computers. I took different test projects and my own project. All of them are not working

## Steps to reproduce
1. open any test project on the last version of macos
2. select export
3. Choose Webview 2 export
4. download archive 
5. run exe on windows
6. Error: Failed to load package.json. Check the file is in the same folder as the app

## Observed result

I receive an error. Tried the same on Windows and the build works fine

## Expected result

Build should run on windows

worked in 3.68 but stopped from 3.70

## System details

MAC OS : 14.2.1, Macbook pro 16 M1 Pro

<details><summary>View details</summary>

It is very annoying. Because I must switch between laptops and it makes me mad. Please fix it asap. I suppose tons of users (developers) works on mac os.

Platform information
Product: Construct 3 r372.2 (beta)
Browser: Safari 17.2.1
Browser engine: WebKit
Context: webapp
Operating system: macOS 10.15.7
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15
Language setting: en-US

Local storage
Storage quota (approx): 77 gb
Storage usage (approx): 22 mb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Idle callbacks are not supported. Background loading performance may be degraded.
Determining input device capabilities is not supported.
WebGL information
Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Apple Inc.
Renderer: Apple GPU
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 511
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_clip_cull_distance
WEBGL_compressed_texture_astc
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_compressed_texture_pvrtc
WEBKIT_WEBGL_compressed_texture_pvrtc
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

H.264 (video/mp4; codecs=avc1.42E01E)

</details>

**Comment by AshleyScirra** [comment]
I exported the 'Ghost shooter' project for Windows WebView2 on Chrome/Windows, Chrome/macOS and Safari/macOS. I then transferred all three zips to a Windows machine, extracted them, and ran them. All three ran fine. So it seems to be working fine for me - which isn't surprising, because it generates the same zip regardless of which browser or OS you are using.

Make sure you are not extracting the zip on macOS. Windows and macOS have different file permission mechanisms and in general if you extract a Windows app on macOS, or a macOS app on Windows, it essentially corrupts it. It's not clear exactly what you are doing between steps 4 and 5 in your description, as you don't describe how you get the app from the macOS machine to Windows, but if you are extracting the zip on macOS and then transferring it to Windows that will probably cause the problem. Make sure you transfer the exported zip file from macOS to Windows and then extract it on Windows, and it should work, as it does for me.
