### ISSUE TITLE
Action for "Set Frame" isn't accepting the frame's Tag, is only working with the frame's number.

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-bugs#7703]
## Problem description

I gave each frame in my sprite a tag, but when I go to "Set Frame" action, it's only accepting numbers and not strings, perhaps this was an oversight. 

Or maybe there was meant to be another "Set Frame" action but it accepts only strings, so you can set it based on the Tag you assigned the frame?

## Attach a .c3p

[bug_set_frame_tag.zip](https://github.com/Scirra/Construct-bugs/files/13802657/bug_set_frame_tag.zip)

## Steps to reproduce

1. Attempt to set frame with the sprite to "frog"
2.
3.

## Observed result

![image](https://github.com/Scirra/Construct-bugs/assets/5744908/42c6c73e-794b-4429-af02-f4cff1a2dbf1)

## Expected result

Should be able to set frame to "frog"

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by XHXIAIEIN** [comment]
This is a suggestion that has been posted on https://construct23.ideas.aha.io/ideas/C23-I-412

**Comment by alastajj** [comment]
@XHXIAIEIN  Part of the issue of posting tiny simple little things on that site is that they're not big flashy features that people flock to vote on. 

So they get ignored.

**Comment by AshleyScirra** [comment]
This is just that the 'Set frame' action has only ever accepted a number, and tags are a newer addition and the 'Set frame' action was not updated. Giving multiple frames the same tag is allowed, so it's not necessarily clear which should be chosen in that case; the first is the obvious answer, but it's not necessarily what (especially if the animation is playing backwards). So I don't think it's that obvious a change to make. I think this qualifies as a feature suggestion so closing. In general I do not want to implement a feature just because it was submitted as an issue, because this bypasses the entire feature suggestions platform, and will only encourage other people to start posting suggestions as issues, and defeat the whole purpose of having separate bug and feature request tracking.
