### ISSUE TITLE
User media can't get camera feed on Galaxy devices

### ISSUE THREAD

**Issue by technofou** [Scirra/Construct-bugs#7716]
## Problem description

User media is able to get the camera feed for iPhones and Pixel devices, but not for Galaxy devices. The green indicator does light up after permission is given, but the feed is black.

## Attach a .c3p

Exporting the official Scirra User Media example project with Cordova.

## Steps to reproduce

1. Take the official User Media example project
2. Export with Cordova
3. Run on a Pixel device (cameras are detected and the feed is shown)
4. Run on a Galaxy device (the list is incomplete, green indicator appears, but feed is black)

## Observed result

Permission is asked, but even when granted 3 different Galaxy devices tested across OneUI 4 & 5 were unable to show the camera feed.

## Expected result

For the camera feed to appear, especially when using the official example project, regardless of the Android device.

## More details
We thought at first that it was a privacy issue with the brand-new version of Android, but unfortunately, our Z Flip 5, S23 Ultra and S20 Ultra all failed to properly show the camera feed. Exporting to an Xcode project worked for iOS devices.

At first we thought it was the code for our game, but trying with the official Scirra User Media example file didn't fix the issue and highlighted the problem with Galaxy devices.

**Affected browsers/platforms:** Samsung Galaxy (One UI) Android devices.

**First affected release:** Did not test with different Construct versions

**Comment by AshleyScirra** [comment]
If it works on other devices but not Galaxy devices, then this is probably a bug with those devices specifically, as if the problem was with Construct it would affect other devices too. I will take a look on one of our Galaxy devices shortly, but even if I can reproduce the best bet might be to file it with Google at crbug.com.

**Comment by AshleyScirra** [comment]
The only Galaxy device we have in the office at the moment is a Samsung Galaxy S8 running Android 9. This does not reproduce the problem: an exported debug APK can access camera feed OK on that device.

I tested both an Asus Zenfone 8 with Android 14 and the Samsung Galaxy S8 with Android 9, with the 'Camera input' example, in both Remote Preview in the browser and exported as a debug APK. In all cases everything worked for me. Note that as the 'Camera input' example also makes use of microphone input for recording, then when exporting you must check both camera and microphone permissions, and approve both requests when using the app, otherwise the permission request may fail and no camera feed will be accessed.

As this older Galaxy device does not seem to be affected it doesn't seem true that *all* Galaxy devices are affected, but perhaps only newer ones are. We don't have any such device to test at this time though, and my best guess is that as it seems to be working in most other cases, that would be a bug with those device's code rather than with Construct, and so the issue will need to be reported to either Samsung or Google.

**Comment by technofou** [comment]
> The only Galaxy device we have in the office at the moment is a Samsung Galaxy S8 running Android 9. This does not reproduce the problem: an exported debug APK can access camera feed OK on that device.
> 

The S8 is an 8-year-old device with 0.22% marketshare running an outdated version of Android; I am not sure why this device is still used to test and validate current market conditions.

I do understand on your side that "it works", but you tested it on a very niche device (the Zenphone) and an outdated and obsolete device (the S8). The majority of Android customers today will face this issue, and that is with your current example and recommended implementation compiled using your provided tools.

This is not a Samsung issue because the majority of apps still run the camera feed without issue. This is a Construct/Cordova issue where something isn't working with the number one used Android devices currently sold.

The Scirra team should possess and test on a real-world current average modern Android smartphone, which would be around a Samsung Galaxy S21+. 

Please reconsider properly testing with a current smartphone.

**Comment by AshleyScirra** [comment]
If it works on other devices usually that indicates Construct's code is correct, as if Construct was doing something wrong, it would affect all devices. I tested both an old device and a modern device, verifying Construct is compatible with both old Android versions and the latest Android version. So there is no evidence of Construct doing something wrong or having any kind of Android compatibility issue with either new or old devices. Perhaps there is an issue with some specific Samsung devices, but if there was, it's unlikely we could do anything about it, as if the problem is with the device, drivers or system, that is beyond our control, and device-specific issues usually are. So I'm afraid the best option in this case is to report it to Google or Samsung.
