### ISSUE TITLE
Debug preview doesn't work if you have no internet connection.

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-bugs#7721]
## Problem description

My ISP has some issues and the internet is disconnected for a few hours every day. Usually I open C3, do some work, disconnect while C3 and preview are open, then I try to run Debug Preview but it doesn't show anything.

Console shows an exception is thrown because C3 couldn't fetch `ui.html` (debugger UI).

I am using C3 Chrome App and it said this version of C3 is ready to be used offline.

## Attach a .c3p

(New Project)

## Steps to reproduce

1. Open C3
2. Run normal preview
3. Disconnect your internet completely
4. (C3 will show that you are not logged in)
5. Run debug preview

## Observed result

Debug preview will not run, and the console will show an error for failing to fetch `ui.html` (or similar file).

## Expected result

These files should be cached when the version launches.

## More details

**Affected browsers/platforms:** Chrome app

**First affected release:** current stable

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by WilsonPercival** [comment]
I have already reported a similar report: https://github.com/Scirra/Construct-bugs/issues/7288

I have now tried clearing the cache, waiting for it to load and opening the preview. Next, I turned off the Internet and tried to create a new project, but again I cannot create a new project.

**Comment by AshleyScirra** [comment]
It's documented that you need to preview while online to ensure the proper resources are cached: https://www.construct.net/en/make-games/manuals/construct-3/getting-started/get-construct-3

I think this applies to debugging as well, so you will need to debug once while online for it to work when you go offline, presumably for the same reason.

IIRC this is due to some weird behavior in the way that browsers cache resources in other contexts - I'm not sure there's a good workaround to it.
