### ISSUE TITLE
Opening a html link from the preview results in it crashing

### ISSUE THREAD

**Issue by therealPaulPlay** [Scirra/Construct-bugs#7741]
## Problem description

When you add a link in an html object and click it in the preview, it opens the link and then crashes.

## Attach a .c3p

[HtmlLinkCrashesPreview.zip](https://github.com/Scirra/Construct-bugs/files/13929160/HtmlLinkCrashesPreview.zip)

## Steps to reproduce

1. Create an html object
2. add a link using html (<a href="https://test.com">test link</a>)
3. click it in the preview

## Observed result
The preview crashes a few seconds after opening the link. 

## Expected result
It should not crash, just like when you do the same thing with the browser object (which works fine)

## More details
Chromium, has been broken for years afaik

**Comment by AshleyScirra** [comment]
It's not crashing: Construct is intentionally closing the preview window. Normally the editor communicates with the preview window by posting messages, to detect things like if preview is active, implement restarting preview, etc. If the preview window is closed - or as a fail-safe, if it stops responding for a period of time - it assumes that preview has ended (or possibly crashed). This is important to ensure a subsequent preview still works even in the event of a crash, since if Construct gets stuck thinking it's still running a preview when it's not, then you won't be able to start a new preview. Navigating the preview window to a new URL has the effect of unloading the preview page (which may look the same as a window close) and will stop the preview window responding to the editor because the new page is not coded to do that (which looks like preview stopped responding).

The Browser object is not affected by this because even when you use a 'Go to URL' action, which normally navigates the same window, in preview mode it still opens the link in a new window, specifically to avoid this problem. You can bypass this and still navigate the preview window by using a custom HTML link, or JavaScript to navigate the page; in this case Construct lets you navigate the page mainly because it's hard to stop you doing that if you really want to, but that will cause the preview to terminate. You can add `target="_blank"` to open the link in a new window for testing purposes, and likewise use `window.open()` instead of assigning `location` in JavaScript, but in these cases Construct doesn't try to force what you do.

**Comment by therealPaulPlay** [comment]
That makes a lot of sense! Thanks for the explanation.
