### ISSUE TITLE
Cordova "iOS Scheme: Legacy (file:)": App won't go past Cordova loading screen on iOS

### ISSUE THREAD

**Issue by therealPaulPlay** [Scirra/Construct-bugs#7749]
## Problem description

The app is stuck on the white cordova splash screen with the icon showing. I've also tested this with different loading styles, scaling types etc. and it does not seem to make a difference. According to Xcode, this is because the plugin File is taking forever:

THREAD WARNING: ['File'] took '853.573099' ms. Plugin should use a background thread.

## Attach a .c3p

[CantGoPastC3LoadingScreenLegacyCordova.zip](https://github.com/Scirra/Construct-bugs/files/13967361/CantGoPastC3LoadingScreenLegacyCordova.zip)

## Steps to reproduce

1. Create a project and fill in all the necessary details (name etc.)
2. Set the Cordova Scheme to Legacy
3. Export the app and open it -> doesn't go past the splash screen (the cordova one, not c3)

## Observed result

The app is stuck on the Cordova splash screen

## Expected result

The app should launch like it does with cordova scheme: modern (though this has a blackscreen issue: #7748)

## More details
Testing in r375

## System details
Currently exporting from firefox, chromium is affected too. Same behavior on multiple computers. 

PASTE HERE

</details>

**Comment by therealPaulPlay** [comment]
Note: at least for me, this isn't super high priority, as I'm using Modern for everything that I'm building.

**Comment by Tarek200** [comment]
I can confirm that when using ------ > (Cordova iOS Scheme = Legacy) 

**On r368.2**
The App Loads normally

**On r369**
The App Freezes on the loading screen


So the issue of the black screen starts from r369

**Comment by AshleyScirra** [comment]
The problem in this case is recent releases enabled worker mode on iOS, but it actually only works in apps with the modern app: scheme, and cannot be supported with the legacy file: scheme as that mode is too restrictive to allow worker mode to start up. You can work around it in current releases by changing "Use worker" to "No" in Project Properties. This should be fixed in the next beta, which will force worker mode off when exporting to iOS with the legacy file: scheme.
