### ISSUE TITLE
Find results don't update on group/variable change

### ISSUE THREAD

**Issue by brushfe** [Scirra/Construct-bugs#7758]
## Problem description

In the Find window, the results update in real-time when events are changed. However, when changing variable or group names, the results don't change. This creates a confusing mix of live/out-of-date find results, which causes particular problems when changes names across a large project.

## Attach a .c3p

https://drive.google.com/file/d/1UIn7qeQOtobOd8wq6aH6z0xfwZ_s42ou/view?usp=sharing

## Steps to reproduce

1. Open the attached project and press Cmd/Ctrl + F.
2. Enter "Folder" as the search term.
3. In the event sheet, change the action parameter from "Folder 1" to "xyz".
4. Note the Find window results have updated.
5. Change the Group Name and Variable name to "xyz".

## Observed result

The Find results don't update when the group and variable names are changed.

## Expected result

The Find results are always live, reflecting every change made, not just changed events.

## More details

**Affected browsers/platforms:** Chrome 120, MacOS 13.4

**First affected release:** Broken in r375, and as far back as r350

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by WilsonPercival** [comment]
If you click on this button, it will update.

<img width="184" alt="image" src="https://github.com/Scirra/Construct-bugs/assets/91274932/7f90a51c-7299-4d47-b987-09d783924481">

**Comment by brushfe** [comment]
> If you click on this button, it will update.
> 

Thanks for that! It seems like Find results are meant to update without pressing that button, but aren't in some cases, so I assumed that's a bug (and not half a feature)

**Comment by AshleyScirra** [comment]
This is currently by design - some things update the results list automatically, such as deleting items, mainly to avoid bugs when trying to navigate to deleted results. (As it happens, editing an action is internally represented as adding a replacement action and deleting the old one, which triggers the reload on the delete as a sort of accidental side-effect.) However there are dozens of possible actions that could affect the results list. Tracking them all down and updating the results list automatically could prove to be a significant amount of work and result in a lot of follow-up bugs of "XYZ doesn't automatically refresh the results list". Instead the "Reload" button is there so you can click it and make sure the results list is up-to-date. As fully automatic refreshing could prove to be a significant work and wasn't intentionally implemented, that is not a bug and would be best filed as a suggestion.

**Comment by brushfe** [comment]
@AshleyScirra Roger that, thanks! What an interesting side-effect of the process. I'll put my best guesses at the most common refresh triggers (folder, variable) into a feature request.
