### ISSUE TITLE
Error displaying shadowcaster shadows after R285

### ISSUE THREAD

**Issue by hcatarrunas** [Scirra/Construct-bugs#7775]
## Problem description
Opened an old example of using the shadrowcaster to add simple "3d" for platformers, and noticed the shadows were getting "stuck" in some places. After some testing i found out the last C3 version the shadows move correctly is R285. From R286 forward (including latest beta) the error happens.
Also confirmed the bug happens in other users of the discord channel.

## Attach a .c3p
[ShadowsForDepth_old_285_ok.zip](https://github.com/Scirra/Construct-bugs/files/14044346/ShadowsForDepth_old_285_ok.zip)

## Steps to reproduce
1. Open and run the example in R285 to see it working ok.
2. Open and run example in R286 to latest beta and see the shadow errors.

## Observed result
If opening in R286 and later, while moving the player the platform shadows get stuck in some positions.

## Expected result
Shadows should update normally like in R285.

## More details
Uploaded video on youtube: [ Shadows error ](https://youtu.be/5MXOSkB2xMo)

**Affected browsers/platforms:** 
Tested on editor, in windows 11, chrome and edge.

**First affected release:** 
Worked in r285 but broke in r286

**Comment by WilsonPercival** [comment]
Worked in `r285-3s`.

**Comment by AshleyScirra** [comment]
The problem here is the Shadow Light object already tries to position itself in the middle of the viewport for rendering shadows anywhere on-screen; it only moves the light position when it detects 'Set position' being used to move the object somewhere else; and this project uses 'Set position' to position the light in the middle of the viewport, which is where it's automatically positioned. This means it only moves the light when floating point precision errors happen in different calculations, which makes it update semi-randomly, and all r286 did was change some details about how the viewport is calculated so probably meant the floating point precision errors happened differently. You can work around it by setting the light position to `scrollx + 0.01`, which means it always detects it being moved to somewhere other than the default position.

I think the real problem here is for this case there isn't a good way to explicitly set the light position, as it happens to match the automatic object position. To resolve that I've added a special 'Set light position' action which avoids this problem entirely. As this appears to be a relatively minor and long-standing issue and we are getting close to a stable release now, this has been added for the next release cycle (first beta release after next stable release).
