### ISSUE TITLE
Press 'Tab' will change the focus, leaving C3

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#7785]
## Problem description

I registered the 'Tab' button as a shortcut key. However, the browser or system will move the focus to another. This will cause C3 to lose focus.

This is the same result in other Preview methods. (Popup windows, Brower tab, Dialog). This inconvenience when previewing the project.

## Attach a .c3p

[issue-press-tab.c3p.zip](https://github.com/Scirra/Construct-bugs/files/14075283/issue-press-tab.c3p.zip)

## Steps to reproduce
1. Preview the game, then press the 'Tab'

## Observed result

C3 to lose focus.

## Expected result

C3 will actively block the 'Tab' key unless it is needed in HTML elements.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by WilsonPercival** [comment]
[workaround7785.zip](https://github.com/Scirra/Construct-bugs/files/14075862/workaround7785.zip)

**Comment by AshleyScirra** [comment]
The browser interprets Tab as a shortcut key to move focus. I'd advise against overriding that, as it is an important accessibility feature (e.g. you will not even be able to tab between input fields in the same project if you override the Tab key). It's currently by design that Construct allows the default browser shortcuts.

Construct does not yet provide a feature to override the browser built-in shortcuts like Tab and F5. However you can override it with custom JavaScript code like this:

```js
window.addEventListener("keydown", e =>
{
	if (e.key === "Tab")
		e.preventDefault();
});
```
