### ISSUE TITLE
Renaming custom actions crash the editor

### ISSUE THREAD

**Issue by cb130felix** [Scirra/Construct-bugs#7796]
## Problem description

Renaming a custom action  under specific circunstancies crashes the editor.

## Attach a .c3p

Not needed, it's very easy to reproduce on a fresh project

## Steps to reproduce

1. Create a new project
2. Add a sprite to the project
3. Into the event sheet create a custom action for the sprite created
4. With the window to edit the custom action properties open use the mouse to place the text cursor into the "Name" field
5. Press enter to confirm the custom action changes (no need to rename the action name)
6. Notice editor crashing
![image](https://github.com/Scirra/Construct-bugs/assets/11541816/4b94af03-542d-4a0d-a2f3-1adebbacd384)

## Observed result

Editor crashes after following the provided steps (reproduced it with consistency)

## Expected result

For the editor not to crash

## More details

I'm on chrome 121.0.6167.86 64 bits, windows 11, C3 r377

**Comment by AshleyScirra** [comment]
I realized my version of Chrome was still on v120. After updating to v121 this reproduces as a tab crash with STATUS_ACCESS_VIOLATION, which is what I assume you mean by "editor crash" (this is actually a browser crash, not a Construct crash). So unfortunately it looks like a Chrome bug very similar to #7321 has reappeared in v121+.

I've filed it with Google here: https://bugs.chromium.org/p/chromium/issues/detail?id=1523691
Unfortunately I don't think there's anything we can do about it - we don't know why it's happening and the normal browser developer tools can't investigate browser crashes, which usually that means it's infeasible to work around. Google will have to provide a fix. In the mean time, it looks like Firefox isn't affected, so that's an option if this is causing problems, or if you can find a way to stay on/reinstall Chrome v120 then that should avoid being affected too.

**Comment by Ldwebster111** [comment]
This is also happening with functions when you edit the category field and press return. Doesn't seem to affect the description field though, and doesn't crash if the category field is left blank.

**Comment by Drednort** [comment]
Also experiencing this issue, will switch to Firefox and hope it gets a fix soon!

**Comment by Laserwolve** [comment]
It seems a workaround for this issue (at least for functions) is to choose the function name from the dropdown, and don't type it manually.

**Comment by Ldwebster111** [comment]
Oh, it's easy enough to avoid once you're cognizant of the fact. Part of the issue though is when you're running on auto-pilot and hit enter without thinking.

Considering this is a browser bug and unable to be fixed Scirra side, I'm wondering if instead it's possible to disable enter on those fields?

**Comment by AshleyScirra** [comment]
Update from Google: this should now be fixed in Chrome 122+. It does not reproduce for me any more with Chrome beta v122.0.6261.29, so you can use that for the time being to avoid the problem. v122 is [scheduled](https://chromiumdash.appspot.com/schedule) for stable release on Feb 20, so it should be fixed on the stable channel in ~2 weeks from now.

**Comment by Drednort** [comment]
Happy days, thanks for the update.

**Comment by AshleyScirra** [comment]
Chrome v122 is now stable. You can make sure it updates by going to Menu - Help - About Google Chrome.

**Comment by jgordos** [comment]
It also happens in Edge; I don't know if it's fixed there.

**Comment by AshleyScirra** [comment]
Chrome and Edge both use the Chromium browser engine, so bugs like this are generally consistent between them. Updating Edge to v122+ should also avoid the problem.
