### ISSUE TITLE
Xbox WebView2 not working on my game

### ISSUE THREAD

**Issue by Pedro1234-code** [Scirra/Construct-bugs#7823]
## Problem description

I've been working on this game for a school work since last year. My goal was to release on Xbox as soon as WebView2 was ported to this platform. The game was even initially meant to be played on Xbox because I full support for gamepad. Once Construct 3 beta officially added support for it, I exported. Works perfectly on PC. On Xbox the launch screen is just black with nothing appearing, only the "Play" button appear on the screen. However the background music plays.

## Attach a .c3p

[Viajante Espacial.zip](https://github.com/Scirra/Construct-bugs/files/14238604/Viajante.Espacial.zip)

## Steps to reproduce

1. Export the game UWP WebView2/Xbox.
2. Deploy it on Xbox using Windows Device Portal.
3. Run it.

## Observed result

Only sound plays in the launch screen and nothing appears except the Play button. The background image is just black.

## Expected result

I expected the game to run and play normally with the same behaviour as WebView2 PC.

## More details

Only happens on Xbox WebView2. PC WB2 works absiolutely normal.

**Affected browsers/platforms:** 

WebView 2 on Xbox.

**First affected release:** 

r378.

## System details

Xbox Series S.

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
See also: https://github.com/MicrosoftEdge/WebView2Feedback/issues/4370

**Comment by AshleyScirra** [comment]
It seems to work fine for me on my dev kit Xbox One. The game goes through the Construct 3 splash, then shows the title screen with everything appearing correctly and matching how it appears on Windows. If I press A then it proceeds to the game and shows some new content.

Maybe make sure your Xbox is up-to-date with any available software updates. It's possible there is some issue specific to the Xbox Series S, but I don't see any issue on the Xbox One, and if it works on Windows but doesn't work on Xbox then that usually is good evidence the problem is with the Xbox and not with Construct, in which case Microsoft will have to fix it. I see that you also filed https://github.com/MicrosoftEdge/WebView2Feedback/issues/4370 so I'll post my findings there too and leave it up to Microsoft to review further.

**Comment by Pedro1234-code** [comment]
The version that I provided here is a highly stripped down version of the original project. In comparison, the original one sizes approximately 108 mb. 

I really don't think it's an specific issue to the WebView2 implementation on Series S but I think it could be related to some problem on loading the textures/sprites with their size or loading the game with its original size. I know someone in the group of people that is making the game that has a One S, I will ask him to try sideloading it for me to check, but I don't believe it's related to the console. I also think it's more likely to be an issue with WebView2 Xbox's implementation than Construct 3.

**Comment by Pedro1234-code** [comment]
@AshleyScirra I just published the game on the Microsoft Store for Xbox so more people could test without having to enable Developer mode. It's called "Viajante do Espaço", you can just search. Would be great to see if it reproduces or not on the full sized version on Xbox One.

**Comment by Pedro1234-code** [comment]
@AshleyScirra Just to add, I'm also unable to play anything in the game preview on Edge on Xbox. The tab of the game just closes.
