### ISSUE TITLE
hierarchy, transform opacity doesn't work when child parent start with opacity 0

### ISSUE THREAD

**Issue by paala** [Scirra/Construct-bugs#7825]
## Problem description

hierarchy, transform opacity doesn't work when child parent start with opacity 0

## Attach a .c3p
[](url)
[transform opacity.zip](https://github.com/Scirra/Construct-bugs/files/14271682/transform.opacity.zip)

## Steps to reproduce

1. start the game, press G or H.. See that child object gets opacity from parent
2. quit game, make both parent and child opacity 0 in editor
3. start game again, press G and H and notice that child doesn't take opacity from parent

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
This is working as intended.

In hierarchies the final opacity of an instance is given by the formula:

**Own opacity** * **Parent opacity**

Ej. 
   Own opacity = 0.5
   Parent opacity = 0.5
   Result opacity = 0.25
   
If the child's own opacity is set to 0 in the editor (or at runtime), it doesn't matter what the opacity of the parent is then, the result will always be 0 because **0 * _anything_ = 0**
