### ISSUE TITLE
Platform issue with Timeline movement and collisions.

### ISSUE THREAD

**Issue by dupuqub** [Scirra/Construct-bugs#7834]
## Problem description

A. When the engine detects a collision between a "Platform" object (e.g. the player) and a "Solid" object moving by Timeline, the Platform behavior cannot properly detect walls.

B. This issue presents itself visually as well. When a Player jumps to a moving wall (a "Solid" moving through timelines) the wall is corretly identified, and the movement of the player is correlated to said "Solid", but when jumping while being "dragged" by this moving object, the next collisions will be evaluated incorrectly and will display the player with some distance to the moving wall, while the player is still being dragged by it.

## Attach a .c3p

[Platform_Timeline_Bug.zip](https://github.com/Scirra/Construct-bugs/files/14304066/Platform_Timeline_Bug.zip)

## Steps to reproduce

1. Press "A" and "D" to move sideways and "Space" to jump.
2. You can wall-jump, so jump from the moving wall.
3. Jump from the moving wall so that it can hit you again mid-jump.
4. Notice that some collisions with the moving object show there was a wall, but others don't, even though clearly you hit a solid on the sides of the Platform object.
5. Also notice that in a first collision from the floor the player's position is correlated to the moving object, but after a second jump it creates a gap between the two.
6. Please observe [this gif](https://giphy.com/gifs/enfZCiNm36orrHO57i) below for clarification.

## Observed result

Timeline objects exist in a timeframe that does not work with the Platform behavior consistently.

The first time you collide with a moving wall, the Player will appear to correctly match its displacement, but at other times it won't, as seen in the gif.

I even tried setting the player's X further away so the collisions were even more visually noticeable, but still the problem persists.

![Capture](https://github.com/Scirra/Construct-bugs/assets/34659544/615526de-e3b9-46dd-8a8e-d1f46db458c7)
[gif showing the effects of this addition.](https://giphy.com/gifs/uLT79A2PFNmINKhVbq)

## Expected result

Uniformly having the player be touching the moving wall, and not ever having a gap depending on whether the jump started from.

It was explained to me in a different issue that there is "no right answer" regarding this matter of timeline movements, but I believe this issue shows inconsistency of behavior rather than a uniform representation of what it aims to do.

## More details

**Affected browsers/platforms:**  Version 121.0.6167.184 (Official Build) (64-bit)

**First affected release:** r379

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by dupuqub** [comment]
As a side note, the issue is also present within the Platformer/MoveTo interaction, which makes me believe that the issue is in Platform and not the other behaviors.

**Comment by dupuqub** [comment]
This is probably of no relevance, but I've been making a custom platform behavior to specially deal with moving parts and had the exact same issue, it was resolved by cancelling Vector_X when hitting objects sideways.

Unfortunately it can't be applied to the traditional Platform behavior because there's not a reliable detection system since walls are not recognized in this case, but maybe internally this is a possibility.

**Comment by AshleyScirra** [comment]
This is another really complicated issue that I think probably comes down to sequencing, but I think it also involves your own event sheet logic.

It is worth remembering that collisions do not happen neatly: as the game ticks it advances in steps. When a collision happens they are usually not exactly touching neatly, they are in fact intersecting by some small distance. The Platform behavior has extremely complex and carefully tuned logic to deal with this and make it act *as if* it really collided exactly on the edge of an object.

When you check if the player is by the wall, it is really saying "is it the case that I am not overlapping anything now, and if I move slightly to the side it is overlapping something, and also still overlapping slightly to the side and up a bit in order to rule out slopes". In "On collision", the objects are really intersecting by some distance, and "move slightly to the side" may or may not cover that distance. It depends on the luck of how the stepping worked out. This could cause inconsistent detection. A better approach might be to use "Is overlapping at offset" and tune the offset to get the right detection.

Further, the wall jump logic appears to set the X vector to exactly match the speed of the horizontally moving obstacle. It looks like the intent is to make the player jump in a reverse direction to the side the wall is on; however the speed is not enough to out-pace the movement of the obstacle, so a wall jump off a moving obstacle actually sets the player to exactly the same speed and direction as the obstacle, so they won't get clear of it. As there are now two moving objects close to each other, the Platform behavior collision handling probably has a tough time working out what to do with this obstacle that keeps overlapping it while moving exactly the same speed as it. It has some fallback logic to get itself out of solids, and I'd guess it's doing that to get clear of the obstacle, but that can end up leaving a margin depending on the algorithm it chooses for the situation and the sequence of ticking. I don't see why you'd do this in a real game though - surely you want the player to be able to jump clear of the obstacle? If you set the player max speed to 2000 (fast enough to outpace the obstacle), then it seems they can jump clear just fine and everything seems to work a lot better. So it seems you've hit an odd edge case of trying to wall jump exactly matching the speed of the obstacle without getting clear of it.

So I think this is just an awkward mix of tricky collision detection and some specific game design choices. I think with the right mix of settings and events you can work around it, and I don't see anything obvious to change about Construct, so closing.

**Comment by dupuqub** [comment]
@AshleyScirra  I'm sorry, but I strongly disagree with this having anything to do with my game logic. There are clearly a situation where a wall pushes a sprite away while not touching it, neither visually or internally. It's not about getting clear of the object, it's about getting pushed consistently and having consistent internal feedback of what is happening, i.e. the wall is pushing the sprite.

On the point of "why" would I want to do this, platform games have been dealing with moving platforms for a long while. And fortunately or not I had to setup my own platform behavior that is working as intended, where walls that are moving you are in fact touching you in the frames you'd expect, having visually and internal consistent feedback of positioning and state.

I understand it's impossible and unrealistic to compare a behavior that has to work with multiple others and a custom build, but this is clearly a nasty bug that limits everyone that tries to deal with moving platforms in the future.
