### ISSUE TITLE
Gamepad and Keyboard difference of input.

### ISSUE THREAD

**Issue by dupuqub** [Scirra/Construct-bugs#7841]
## Problem description

In this minimal repro, the Player's height is higher when jumping with a Gamepad then with a Keyboard.

![Capture](https://github.com/Scirra/Construct-bugs/assets/34659544/1fce55d9-ce25-4984-a709-07a1f181cc75)

## Attach a .c3p

[Gamepad_Keyboard.zip](https://github.com/Scirra/Construct-bugs/files/14320907/Gamepad_Keyboard.zip)

## Steps to reproduce

1. Just press "Space" on a Keyboard or "A" on a Gamepad to jump.
2. Observe the values for "Player.Platform.VectorY" on the text.
3. Observe the difference of values when jumping with Gamepad and Keyboard.
4. There's a sensor that changes color when you hit, but Keyboard doesn't reach it, only Gamepad.

## Observed result

Different values arising from what I imagined to be universal code.

## Expected result

Uniformity in values.

## More details

**Affected browsers/platforms:** 
Version 121.0.6167.185 (Official Build) (64-bit)

**First affected release:** 
r379

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
There is currently a subtle difference between gamepad input and keyboard input. This has come up a few times before, and is quite unfortunate, but it's a tricky problem.

Fundamentally most inputs fire events. However for some reason the browser's Gamepad API relies on input polling (i.e. having to regularly retrieve the current state and identify changes). Due to the use of input polling, 'On gamepad button pressed' is a "fake trigger": it looks like a trigger but it actually runs like a normal condition in the event sheet top-to-bottom execution. It really means "is a button down that was not previously down" rather than "on a button event fired by the browser".

This causes a difference in the way your event sheet is processed. It ends up being processed like this:

1. Keyboard triggers happen (i.e. 'On space pressed')
2. The Platform behavior ticks
3. The event sheet is executed - and note that this is where 'On gamepad button pressed' will be run

Notice that the inputs happen either side of the platform behavior being ticked. Normally this is not a problem: if pressing the gamepad causes a jump, then the jump merely begins on the next tick, and it works the same as keyboard input.

However in your case you have logic for jump holding in the event sheet. (I'm sure you're aware but just to be clear - the platform behavior has a jump hold feature, and if you use that, you won't have this kind of problem...) This means that the position of where you have 'On gamepad button pressed' can affect the logic. With keyboard input it runs 'On space pressed', sets the platform vector Y, then immediately ticks the platform behavior with that vector Y. With gamepad input it runs 'On gamepad button pressed', sets the vector Y, but then it continues down the rest of the event sheet as it is a normal condition; it then processes events regarding the jump hold which modifies the platform vector Y again, and only after that does it tick the platform behavior, which then means the first tick after input of the platform behavior has a different vector Y.

There is a simple workaround: move event 3 (the OR block with the input triggers) to the end of the event sheet. Then it never adjusts the vector Y before ticking the platform behavior.

We could try to adjust how the gamepad API input works, but this is a really tricky backwards compatibility issue: some projects may rely on the current quirk in order to work correctly, and so changing it will actually break them; introducing a secondary set of features is often confusing; and internally it's relying on polling anyway which doesn't map easily on to firing triggers like with Keyboard, Touch and Mouse. Ideally the Gamepad API would actually fire events, but this improvement seems to be a long time coming. So unfortunately I think we're stuck with the current quirk for the time being at least.
