### ISSUE TITLE
CSS vendor prefix is not set

### ISSUE THREAD

**Issue by Gryphonn** [Scirra/Construct-bugs#7890]
## Problem description
CSS vendor prefix is not set via Construct's **Set CSS style action**.

## Attach a .c3p
[cssPrefixBug.zip](https://github.com/Scirra/Construct-bugs/files/14545834/cssPrefixBug.zip)

## Steps to reproduce
1. Open Web Inspector
2. Find HTML-element with the ID **cover**
3. Check its CSS properties. There is **backdrop-filter**. But there isn't **-webkit-backdrop-filter**.

## Observed result
The **-webkit-backdrop-filter** isn't applied.

![image](https://github.com/Scirra/Construct-bugs/assets/21972383/b8d3caca-4244-4094-b888-5a980a1ff83b)

## Expected result
The **-webkit-backdrop-filter** is applied.

![image](https://github.com/Scirra/Construct-bugs/assets/21972383/49b2e9d7-0ef9-4d9b-b862-772d37956bb7)

## More details
1. You can try other CSS properties as well. For instance
porperty name "-webkit-box-shadow"
value "10px 10px"
The result is the same
2. Vendor prefixes work well when you add them in a CSS-file.
3. But sometimes you want you CSS properties to work with dynamic values. That's why it's important to have this feature working in C3 actions.
4. It is still generally necessary to preface certain CSS styles with -webkit and -moz prefixes for browser compatibility. This is because different browsers may interpret certain CSS styles differently, and the prefixes help to ensure that your styles are displayed consistently across different browsers.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Construct assigns CSS styles via JavaScript, i.e. with `elem.style[prop]` syntax, which uses different strings to CSS property names, i.e. it needs to pass `backdropFilter` instead of `backdrop-filter` in that case. There was indeed a bug with how Construct handled vendor prefixes in that case, which is fixed for the next beta. However it appears that even with the fix, the vendor prefixes do not always appear in Chrome's dev tools. I think this is because it either does not support the vendor prefix (e.g. in JavaScript, there is no `webkitBackdropFilter` style property, because Chrome does not support it), or because it is aliased to a standard CSS property (e.g. in JavaScript, the `webkitBoxShadow` property aliases `boxShadow`, so they act as if they are the same `box-shadow` CSS property). In other words changes made from JavaScript behave differently to properties in CSS files, as invalid or unsupported changes are ignored and some vendor prefixes are aliased to standardized properties. So even with the fix it looks like the same thing is happening, but I believe it should be working correctly, as browsers that do support the vendor prefixes will use them.
