### ISSUE TITLE
css not implementing on transparent Layer

### ISSUE THREAD

**Issue by luckyrawatfreax** [Scirra/Construct-bugs#7891]
## Problem description
I added a css file and changing background of transparent layer

## Attach a .c3p
[css_issue.zip](https://github.com/Scirra/Construct-bugs/files/14553546/css_issue.zip)

## Steps to reproduce

1. open attached file 
2. preview it

## Observed result
no background color change

## Expected result
it should change background color

## More details

its working on r368

**Affected browsers/platforms:** 
windows/Chrome

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by Gryphonn** [comment]
Use these CSS styles.

html {
height: 100%;
background: radial-gradient(#814c8c,#382b57);
} 

body {
background: none !important;
}

**Comment by luckyrawatfreax** [comment]
@Gryphonn what was wrong in my css as it is working on old version

**Comment by Gryphonn** [comment]
> @Gryphonn what was wrong in my css as it is working on old version

Due to new HTML features the structure of HTML-page has changed. So we have to deal with it.

**Comment by AshleyScirra** [comment]
The problem here is that Construct sets the background color of both the html and body tags according to the background color specified in Project Properties. You can see this happening in dev tools and it overrides the style in your CSS as style attributes have higher specificity than stylesheets. You can override this using `!important`, e.g.:

```css
html, body {

	background: radial-gradient(#814c8c,#382b57) !important;

} 
```

**Comment by AshleyScirra** [comment]
Actually that's not quite right - it is indeed a breaking change, as since the introduction of HTML layers, the body element ends up with a zero height instead of filling the page, so the background style is not rendered at all. I've changed the next beta to force the body element height to fill the viewport so styles like this continue to work. I'm not sure if there will be backwards compatibility implications to that, but we have a few beta releases to find out.
