### ISSUE TITLE
3Dshapes show seams

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#7900]
## Problem description
3Dshapes show seams where the quads meet, this seems to be caused by smooth filtering as it goes away with nearest filtering.

## Attach a .c3p
[SeamsBug.zip](https://github.com/Scirra/Construct-bugs/files/14605435/SeamsBug.zip)

## Steps to reproduce

1. run preview
## Observed result
seams appearing depending on the angle, you can look through to the bg color. It can sometimes be more and less visible
![image](https://github.com/Scirra/Construct-bugs/assets/89512047/3accba1e-59e3-428c-a9a8-acef29a09e34)

## Expected result
no seams

## More details
This makes a game look bad/artifacty especially if there is a large difference between the color/texture of the shape vs the background.
Maybe a 1 pixel overlap like the 9patch could be considered.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Strange - this seems to only happen in low quality fullscreen mode. It seems fine in high quality mode. The 3D shape faces are rendered exactly adjacent with no gap and so the GPU rasterizer ought to not have any gap between them. So I have no idea why a seam is occurring in this case, so unfortunately this might not be feasible to solve.

**Comment by F3der1co** [comment]
> Strange - this seems to only happen in low quality fullscreen mode. It seems fine in high quality mode. The 3D shape faces are rendered exactly adjacent with no gap and so the GPU rasterizer ought to not have any gap between them. So I have no idea why a seam is occurring in this case, so unfortunately this might not be feasible to solve.

It is still there with fullscreen quality high, but as the seam is 1 pixel it will be a lot less visible!

**Comment by F3der1co** [comment]
![image](https://github.com/Scirra/Construct-bugs/assets/89512047/7ec3873f-9832-43f6-b291-47d3540e9382)
from my game with fullscreen quality high

**Comment by AshleyScirra** [comment]
You're right, it does happen in high quality fullscreen mode, it's just harder to spot.

It does however significantly reduce if you set the downscaling quality to "high". This makes me think it's a variant of the [seams you can get from mipmapping](https://www.construct.net/en/blogs/ashleys-blog-2/surprising-difficulty-1528), but when applying to mipmapping with depth in 3D: the seams come from sampling just outside the edges of the texture on a downscaled mipmap, and downscaling quality "high" helps mitigate that by adjusting the spritesheets.

I don't think there's any better solution - it's just one of many, many extremely complicated things that come up if you start to go down the road of a 3D engine, which is why I'm reluctant to go further along that road...
