### ISSUE TITLE
Play animation (play from begining) doesn't work in 1 case.  simple bug

### ISSUE THREAD

**Issue by ruskul** [Scirra/Construct-bugs#7919]
## Problem description

If you "set animation (play from beginning)" as an action and set the animation to one that is already playing, it will not start from the beginning.

Given the entry in the manual, I would expect that setting an animation to play from the beginning would still work to play the animation from the beginning, even if I was already in that animation.

"Set animation
    Change the currently playing animation to another animation. Animations are identified by their name (case insensitive). The new animation can either play from the beginning or from the same frame number as the last animation was on (current frame)."

## Attach a .c3p

https://drive.google.com/file/d/1PkA_satzrilgZ6CwE_GVH2vM926OxMig/view?usp=drive_link

## Steps to reproduce

You probably don't need a c3p, but here is one for convenience to see it in action.  It is pretty self explanatory.  You can hit play and drag the box around and test the overlap.  If you look at the events you can see whats going on.  I use frame swaps to control the polygon being used.

However, even easier than using the c3p:  Check the code for the plugin:  if the animation name being switched to is the same as the one already playing, it simply returns and does nothing.  This makes total sense- no need to do all that work.  Except if play from beginning is selected, then it should still switch to the starting frame.

## Observed result

Setting an animation to play from beginning doesn't work if you are already in that animation.

## Expected result

I expect "set animation (play from beginning)" to play any animation from the begining, regardless of what current animation I am in.

## More details

I would suppose if the behavior is meant to act this way, that the action description should be updated in the sdk to include something about only working if the animation is different and the manual updated as well, but I think that is less clear.

As it stands, I don't think it is intuitively clear and it took a while to figure out it wasn't my mistake in code.

Thanks!

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
'Set animation' is intended to be used to change to a different animation, and so ignoring the call entirely if it sets the same animation is by design. Even if we wanted to change the design, despite how obvious the code change may seem, it risks breaking thousands of projects designed over a decade or more which depend on the current use of "Set animation" to the same animation with "from beginning" *not* restarting the animation, which is especially likely to be widespread as "from beginning" is the default parameter. Meanwhile if you intend to restart the current animation, you can do that with the existing 'Start' action choosing "from beginning", or in code, `startAnimation("beginning")`.

Therefore I don't believe any functionality should be changed here. However I have added a note in the manual to highlight that the action/method will be ignored if it's already the current animation.

**Comment by ruskul** [comment]
Thanks for the updated manual entry - I figured that the base behavior wouldn't be changed... way to many projects surely relying on it as it is.

Mahalo!
