### ISSUE TITLE
Contains invisible characters in file name, causing the project to fail to be saved.

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#7927]
## Problem description

if folder name contains invisible characters, Can't to be save as projcet folder.

<img width="142" alt="Snipaste_2024-03-28_14-49-09" src="https://github.com/Scirra/Construct-bugs/assets/45864744/8e5fa812-db08-4a77-947a-b49d92b23b2d">

## Attach a .c3p

[issue-invisibleChar.c3p.zip](https://github.com/Scirra/Construct-bugs/files/14785074/issue-invisibleChar.c3p.zip)

## Steps to reproduce

Save as project folder
<img width="477" alt="Snipaste_2024-03-28_14-51-10" src="https://github.com/Scirra/Construct-bugs/assets/45864744/e18f9f80-4ed5-4698-8555-28ab98723595">

## Observed result
<img width="448" alt="Snipaste_2024-03-28_14-52-41" src="https://github.com/Scirra/Construct-bugs/assets/45864744/3ba6a3af-60a5-4b6f-969d-b79c485bc02a">

<img width="798" alt="Snipaste_2024-03-28_14-33-40" src="https://github.com/Scirra/Construct-bugs/assets/45864744/0ab36c4c-c55b-4292-9711-29d384f6f333">

```
mainMenu.js:2  [Project] Exception saving:  TypeError: Failed to execute 'getDirectoryHandle' on 'FileSystemDirectoryHandle': Name is not allowed.
```

## Expected result

Auto remove illegal characters

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
How are you typing this invisible character? Is it something that can normally be entered?

**Comment by XHXIAIEIN** [comment]
```
 
```

**Comment by AshleyScirra** [comment]
It turns out it's not a special character at all - just a normal space.

It turns out that while Construct checks for an invalid trailing space, a leading space is invalid in a filename. In Windows it appears if you try to rename a file with a space at the start, it just removes it. Zip file rules are much more relaxed and allow pretty much anything, but when you write a file to a folder project it must have a valid name, and a space at the start is invalid, which causes the error.

It's straightforward to update Construct to validate that and consider spaces at the start as invalid. However this has complicated and difficult backwards compatibility implications: the provided project no longer opens after the change, as the existing space at the start of the folder name is invalid and so Construct reports it as an invalid project. It is unknown how many projects this will affect in practice. This could potentially be worked around, but it looks like it would require a lot of very complicated code. Therefore this change is being held back for the next release cycle (first beta after the next stable release) to help evaluate the backwards compatibility impact.

In both cases - to allow saving as a project folder, and to work around later releases not opening the project - the workaround is simple: just remove any spaces at the start of any folder or file names.
