### ISSUE TITLE
Discrepancy between preview and export with a certain script setup

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-bugs#7934]
## Problem description

I found a specific setup of scripts that can lead to a discrepancy between preview and export. As preview it works perfectly, but will break upon export.
Basically I had a script for eventimports, that I then also attempted to import into another script so I can use the same functions that I call from events. I guess it's not the most sensible setup, but it works fine in preview so getting that error on export felt odd.

## Attach a .c3p

[scriptbreak.c3p.zip](https://github.com/Scirra/Construct-bugs/files/14864477/scriptbreak.c3p.zip)

## Steps to reproduce

1. Preview project
2. Keeps logging "yes" every tick in console
3. Export (I tried nw.js and webview2)
4. Game crashes/errors/not logging

![image](https://github.com/Scirra/Construct-bugs/assets/31101309/acea534c-dbd1-4434-94c0-f3b017657a61)

## Observed result

Game shows error only after exporting. Scripts then don't work.

## Expected result

Not sure. One way would be to intentionally break previews in that case and call it a day. If it doesn't work on export it shouldn't work in preview. Or the other way around :)

## More details
The file that's marked for "import for events" is moved somewhere else on export and thus the attempt to import it will fail.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r386 (beta)
Browser: Edge 123.0.2420.65
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0
Language setting: en-US

Local storage
Storage quota (approx): 134 gb
Storage usage (approx): 252 mb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA Quadro K620 (0x000013BB) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_clip_control
EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_conservative_depth
EXT_depth_clamp
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_polygon_offset_clamp
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
NV_shader_noperspective_interpolation
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_blend_func_extended
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_polygon_mode
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm;codecs=opus)
WebM Vorbis (audio/webm;codecs=vorbis)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav;codecs=1)
Supported encode formats:

WebM Opus (audio/webm;codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
Supported encode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
WebM H.264 (video/webm;codecs=avc1.420034)

</details>

**Comment by AshleyScirra** [comment]
The problem here is using exports in the 'Imports for events' script file is not actually supported. It should not work in preview - the correct result is to show an error as you see on export. The reason for this is that the 'Imports for events' script file is actually just pasted in to the top of scriptsInEvents.js, which contains all script blocks used in event sheets in the project (and is actually not exported at all if the project does not use any script blocks in event sheets). Therefore the actual file with the purpose 'Imports for events' is not exported at all, and so it cannot be referred to by its filename, and so it cannot be imported, and so exporting anything from it is not supported. This should not matter though - just export from a different script file, and if you need to use it in scripts in event sheets, import it in the 'Imports for events' file (the name being a hint it's for *imports* only).

I've made two changes to fix this: firstly preview does not export the 'Imports for events' script file, matching export, so it will also show an error on preview. Secondly it now highlights any use of exports in the 'Imports for events' script with warnings saying that is not supported. As we are close to a stable release and this is a non-essential change, the fix will be in the next release cycle (first beta after the next stable release).
