### ISSUE TITLE
Can't open Construct 3 games in safari

### ISSUE THREAD

**Issue by aiko3310** [Scirra/Construct-bugs#7950]
## Problem description

I can't open the Construct 3 games in safari

## Steps to reproduce

1. open any construct 3 games in safari
2. will see the console.log error

## Observed result

<img width="542" alt="截圖 2024-04-18 中午12 07 36" src="https://github.com/Scirra/Construct-bugs/assets/25877642/e87d6c54-a6fa-4aca-961b-26dad0372e5a">

## Expected result

Hope to see the game running properly

## More details

I can open the games which made by construct 2

**Affected browsers/platforms:** 

Safari 17.4.1

**Comment by AshleyScirra** [comment]
The report appears to claim all projects are affected. No project was provided so I opened Ghost Shooter on Safari 17.4.1 on macOS. It worked fine and no errors were logged. So this does not appear to affect all projects (which is common, which is why the bug report guidelines require a project).

My best guess: you're using a third-party addon that does not support worker mode. You'll need to contact the addon developer for support.
