### ISSUE TITLE
Following directions causes audio tag bug

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-bugs#7970]
## Problem description

When I went to set a tag I left the expression empty as the instruction said to "leave empty"

But it wouldn't let me click "done" it kept showing an error.

If it's suppose to be another way, perhaps the wording could be clearer

![image](https://github.com/Scirra/Construct-bugs/assets/5744908/994e6c60-64b5-4a8d-a9cb-29aaa6f77fd8)

## Attach a .c3p

[audio_error.zip](https://github.com/Scirra/Construct-bugs/files/15127916/audio_error.zip)

## Steps to reproduce

1. edit the playback rate action
2. leave the tag empty
3. click "done"

## Observed result

Error message

## Expected result

No error message, or clearer instructions

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
In this case **"leave empty"** means using an empty string, as in **""**, which also is the default value.

Not sure if this is consistent across all the documentation as there are places in which the term **"empty string"** is used explicitly and other places of the UI actually accept and empty value.

**Comment by AshleyScirra** [comment]
By default an empty string `""` is entered in that parameter. The description is advising you to leave it there. The error you showed only occurs if you select that empty string and delete it. Empty expression fields are never valid in Construct and so "leave empty" never means "delete the contents of the field" - it's a shorthand for "leave as an empty string".

I'm sure this kind of phrasing is used a lot across Construct and I don't believe it has actually caused much confusion, since you have to take action where it is advising not to take action for there to be an error, so I don't think this warrants any change.

**Comment by alastajj** [comment]
🙄
