### ISSUE TITLE
WinView2 and nw.js exports don't work properly if icon purpose is 'none set'.

### ISSUE THREAD

**Issue by pandabear7413** [Scirra/Construct-bugs#7994]
## Problem description

WinView2 and nw.js exports don't work properly if icon purpose is 'none set'.  
- for nw.js, the game.exe file will work but not the WindowsIconUpdater.exe.
- for WinVIew2, neither the game.exe nor the WindowsIconUpdater.exe will work.

## Attach a .c3p

[Skyrra Squadron Example (4).zip](https://github.com/Scirra/Construct-bugs/files/15242132/Skyrra.Squadron.Example.4.zip)

## Steps to reproduce

- take any sample project
- remove all icons but one
- set that icon's purpose to 'none set'
- export to WinView2 or nw.js

It looks like the following lines don't exist in the package.json file

![c1](https://github.com/Scirra/Construct-bugs/assets/85074714/93030d42-f614-487a-991c-bd605784d5c8)

## Observed result

With WebView2:
- when running the game .exe
![Clipboard01](https://github.com/Scirra/Construct-bugs/assets/85074714/ce3b37a1-d316-4d2e-98ab-c44fca1a78c4)

With WebView2 AND nw.js
- when running the icon updater:
see comment below

**Affected browsers/platforms:**

Windows 10
Version 124.0.6367.119 (Official Build) (64-bit)

388-2, and I *think* 379

**Comment by pandabear7413** [comment]
With WebView2 AND nw.js
when running the icon updater:
![Clipboard02](https://github.com/Scirra/Construct-bugs/assets/85074714/53333a8c-2d0f-4c25-a26e-09060402d054)

**Comment by AshleyScirra** [comment]
Attached file is not an openable Construct project. This one reproduces the issue: [issue7994.zip](https://github.com/Scirra/Construct-bugs/files/15247934/issue7994.zip)
(Please always follow the bug report guidelines as it saves time and reduces confusion)

**Comment by AshleyScirra** [comment]
If your project uses no icons, it is correct that WindowsIconUpdater.exe shows an error: as it says it cannot find any icons to update, as none were specified, which is an unexpected situation (either your project specifies icons, or you don't use any and then don't run the icon updater as there is nothing to update). So that aspect is not a bug.

An NW.js export runs correctly with no icons set. The only actual issue appears to be the Windows WebView2 export does not run if the project uses no icons. This is fixed for the next beta.
