### ISSUE TITLE
 Turret behavior predictive aim bug (Update)

### ISSUE THREAD

**Issue by TackerTacker** [Scirra/Construct-bugs#8062]
## Problem description

The original problem is described in issue #7965 and stays the same

This was part of the comment from that issue
> If you can figure out the correct maths or checks to avoid this case perhaps it could be implemented, [...]

_Originally posted by @AshleyScirra in https://github.com/Scirra/Construct-bugs/issues/7965#issuecomment-2098271114_

Later I answered to that comment but the issue was already closed, so I assume no one saw those comments, that's why I post it as a new issue with those updates.

R0j0hound looked at the math and found solutions for it, he made 2 examples which I posted in these comments
1) https://github.com/Scirra/Construct-bugs/issues/7965#issuecomment-2102814216
2) https://github.com/Scirra/Construct-bugs/issues/7965#issuecomment-2103255831

## Attach a .c3p

See #7965 

## Steps to reproduce

See #7965

## Observed result

See #7965

## Expected result

See #7965

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I've changed the next beta to use a calculation based on **targeting2** from *turret_behavior_aim_bug_and_event_based_solution3.zip* in #7965. Since the old calculation was in place for many years there may well be backwards compatibility implications if the new calculation does not work exactly the same as the old one did, so we'll see how it goes during beta releases, but as far as I can tell it is comparable but better handles extreme situations.
