### ISSUE TITLE
Erroneous pathfinding behavior...

### ISSUE THREAD

**Issue by DieppedalleDavid** [Scirra/Construct-bugs#8063]
## Problem description
The object refuses to move if the rotation option is disabled and rotation speed = 0.
If I reactivate the automatic rotation and set a speed > 0, it works!

https://drive.google.com/file/d/1pk_9NTJm9_ETu1Vlj_dRVLTfnKHxetZ4/view?usp=sharing

Forum:
https://www.construct.net/en/forum/construct-3/how-do-i-8/incomprehensible-behavior-182499#forumPost1109294

Edit: No a bug...

you just need to set a rotation speed above 0, but it will be much too slow, I wonder why this parameter accepts 0 or very low values ???

It's not very clear to me.

**Comment by AshleyScirra** [comment]
The 'Rotate object' property of Pathfinding only affects whether it sets the angle of the object or not. It does not affect the logic of the behavior at all.

If the rotate speed is 0, then the behavior cannot rotate itself to point in the direction of the next node, so it will not move. This is by design.

**Comment by DieppedalleDavid** [comment]
Ok thx.
