### ISSUE TITLE
Enabling/Disabling behaviors is inconsistent in Event Sheets.

### ISSUE THREAD

**Issue by fvcalderan** [Scirra/Construct-bugs#8076]
## Problem description

When using event sheets, enabling and disabling behaviors can differ visually and even operationally. Here are some examples:

![image](https://github.com/Scirra/Construct-bugs/assets/24211835/c0769844-c855-4fdb-bfdf-6da5666588ee)

The last two items being the most different, since they use checkbox instead of combobox to choose between Enabled and Disabled.

## Attach a .c3p

[C3BehaviorsDisable.zip](https://github.com/user-attachments/files/15890948/C3BehaviorsDisable.zip)

## Steps to reproduce

1. Open attached C3P
2. Read the actions
3. Double click each one of them.

## Observed result

Disable actions have different texts and even completely different UIs (MoveTo and Follow vs the rest).

## Expected result

Every disable action should read the same text and share the same UI style.

## More details

This bug report is valid for the C3 Editor in the English language.

**Affected browsers/platforms:**  Every browser and platform.

**Comment by AshleyScirra** [comment]
This is basically down to backwards compatibility, as things like the boolean parameter were introduced after many other behaviors were already finished, and updating existing parameters to new parameters of a different type is complicated. So for now it's by design. If you wish to suggest changes to the existing design, please post a feature request.
