### ISSUE TITLE
DrawingCanvas in Mac

### ISSUE THREAD

**Issue by starkiJi** [Scirra/Construct-bugs#8123]
## Problem description

I don't have a MAC computer, my game publisher sent this text: 
**We've come across a minor problem when playing the game on the newer Apple Silicon Macs. The game text has a pink or purple background color behind it. Please see the attached screenshots. This is only happening on Apple Silicon Macs. The game text is fine on older Intel Macs. image 1 - https://ibb.co/WP1XSHH image 2 - https://ibb.co/YQMJYZW** 
![original](https://github.com/user-attachments/assets/c1d7bd20-3341-4905-9334-fe976136727c)
![original-1](https://github.com/user-attachments/assets/b3b06a37-f9e3-41af-8592-0514e51e18b3)

In these areas I used **DrivingCanvas** and took a paste of the TEXT object.
I removed the **DrivingCanvas** and the problem disappeared.

## Attach a .c3p

[DrawingCanvas and Mac bug.zip](https://github.com/user-attachments/files/16288367/DrawingCanvas.and.Mac.bug.zip)

## Steps to reproduce

1. Launch the game on Mac ( Apple Silicon ) and see the problem. ( Intel Macs work no probelrm )

## Observed result

You will show a bug - an initially transparent area. The **DrivingCanvas** will be pink or another color.

## System details

**r388.2, export - Desktop ( WKWebViev )**

**Comment by AshleyScirra** [comment]
I tried the sample project in Safari on an Apple Silicon mac using Remote Preview, and it doesn't reproduce the problem. The text appears OK on a black background. I'm afraid without a way to reproduce the problem we cannot investigate further.

It may be worth checking if any experimental features or settings have been changed on the affected device - for example if it's had pre-release support for WebGPU manually enabled, that might be buggy (as it's still in development, which is why it is off by default).

Besides, if the problem only happens on one type of device, that is usually a strong sign the problem is with the device software and not Construct, such as a graphics driver bug. If the problem was with Construct itself it would affect all devices, whereas if the problem is something like a graphics driver bug then it will look correct everywhere but look wrong on devices with a broken graphics driver. So in that case I'd suggest reporting the issue to Apple directly: https://bugs.webkit.org/
