### ISSUE TITLE
Data retrieved from JSON is always empty

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-bugs#8136]
## Problem description

In the attached example, at line 21, `t` is always 0, despite the json object having a value in it.
A few things I noticed:
- The CheckSequence function worked fine when it was loading json from a file.
- In the file, array elements were objects, but it seems Json.Push action pushes elements as strings.
- There are escape characters `\` in the json with the array, but when they are loaded into another json object they are gone.
- I am using the debugger to see json contents.

## Attach a .c3p

[test json.zip](https://github.com/user-attachments/files/16374085/test.json.zip)

## Steps to reproduce

1. Run
2. Check the console

## Observed result

always logs `Check Seqeunce::t=0==0` despite `t` having a value

## Expected result

`t` value should be the same as the one in `CurrentCommand` object

**Comment by AshleyScirra** [comment]
This is too complex a project to feasibly debug. Please provide a minimal project as per the bug report guidelines.

**Comment by Alaadel** [comment]
> This is too complex a project to feasibly debug. Please provide a minimal project as per the bug report guidelines.

It is already minimized. I tried a smaller one, but the bug didn't occur.
[test json 2.zip](https://github.com/user-attachments/files/16377512/test.json.2.zip)
1. Click Set
2. Click Get

The 2 projects have generally the same process, but the first one have the bug, while the other doesn't.

The issue is simple: I log the contents of `CurrentCommand`, and it has `t:123`. The next like uses `t=CurrentCommand.Get("t")` and the result is 0.

**Comment by AshleyScirra** [comment]
If it doesn't reproduce in a smaller project, that usually means it's a mistake in your events. This is a pretty common outcome - a complicated event sheet can be hard to make sense of, and even if you think the problem is some kind of obvious error, it can still be a mistake (e.g. #8091 is a good example of this - a case of "comparing equal values turns out to be unequal" was just a mistake involving an OR block). Complicated event sheets with more than a handful of events are extraordinarily difficult to debug in the engine, so much so that really it's infeasible, which is why we require a minimal project is provided. So I'm afraid unless you can provide a minimal project demonstrating the issue occurring it's not feasible for us to investigate, and it seems likely the problem is in your event sheet anyway.
