### ISSUE TITLE
Text icon filtering can make icons look bad in some cases

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#8151]
## Problem description
Text icon filtering can make image icons look bad in some cases. I hope this can be fixed and isn't forced by the text rendering.

## Attach a .c3p
[iconFilter.zip](https://github.com/user-attachments/files/16473905/iconFilter.zip)

## Steps to reproduce

1. start preview
## Observed result
![image](https://github.com/user-attachments/assets/0bffd68f-0302-48ba-82e4-32a818b7827b)
Icon is filtered in a way making it lose its shape a bit and not looking round, on some Icons this can look very bad

## Expected result
icon looks similar to sprite or an option for icon filtering. 
It's a bit difficult as for some cases the super sharp look might be a benefit, in others it seems to really make the icon look horrible

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by F3der1co** [comment]
![image](https://github.com/user-attachments/assets/131f9e9f-091b-4a94-a542-e60ef175de75)
example from real project to more clearly show how it looks off

**Comment by AshleyScirra** [comment]
The problem here is text icons are drawn to a 2D canvas, and that handles downscaling differently. The project is set to use trilinear filtering, which means Construct renders sprites with mipmaps for best quality. However Chrome doesn't currently use mipmaps for downscaling in 2D canvases, so it can't match the quality.

The 2D canvas downscaling quality is ostensibly configured with the `imageSmoothingQuality` option. This defaults to "low", and Construct wasn't changing this for text rendering; I've set it to "high" for the next release to tell the browser to do the best it can. However this still doesn't fix the problem in Chrome, largely because "high" quality mode still doesn't use mipmaps (and [there's a long-standing issue about that](https://issues.chromium.org/issues/40044062)). I'm afraid I think that's the best we can do for now - other workarounds are complicated and would probably kill text rendering performance. With the latest change to Construct, at least if Chrome updates "high" quality mode to really do high quality downscaling then it should look better. Until then one possible other workaround is also to use text icon images at about the same size they are displayed, avoiding significant downscaling, as it's only when an image is resized a lot smaller that it looks bad.
