### ISSUE TITLE
Filter out HTML elements from the Touch/Mouse check clicked object list

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#8170]
## Problem description

There are always newbies who ask why these events don't work and how to make the buttons work.
![image](https://github.com/user-attachments/assets/f7b259ea-8082-4382-8fd2-1e33fe6456bd)

Although we can tell them once or twice that they should use it this way.Then explain again and again that you should use Sprite objects instead of buttons.
![image](https://github.com/user-attachments/assets/dc46aba6-3615-47b8-9356-0e114686d527)

## Attach a .c3p

[button-click-event.c3p.zip](https://github.com/user-attachments/files/16607042/button-click-event.c3p.zip)

## Observed result

but every few days there are new newbies asking this question, it is too frequent.

## Expected result

so, I hope to filter these HTML elements in the list. Because this way will not do any work. Instead, it confuses users, why this doesn't work.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is by design. It exists for a good reason: HTML elements handle input themselves and prevent the input reaching the rest of Construct to avoid input conflicts. For example if you click on a Text Input, it doesn't trigger 'On clicked' for a Sprite object beneath the Text Input: the input HTML element handled the input event. Similarly using arrow keys to move the caret inside the Text Input does not cause movements like 8 Direction to move around for the same reason.

Further, 'On touched object' triggers when the touch/click (aka "pointer") starts; however 'On button clicked' triggers when the pointer is released over the object *only* when the original pointer start was *also* inside the button. Therefore even if this worked there is a subtle difference in the way they work - and in fact using the pointer start is incorrect in that it is not consistent with typical UI interaction, since all buttons work with the release mechanism and users generally expect software to work that way. (This is a good illustration of how [UI is much more subtle and complicated to get working correctly than a lot of people initially think](https://www.construct.net/en/blogs/ashleys-blog-2/simple-software-things-1587): find any button, click on it and drag off, or click outside and drag on, and the button won't activate; you must click on and release on the button
