### ISSUE TITLE
Hierarchy: If a child object set opacity when it created, it will not follow the parent's opacity changes later.

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#8171]
## Problem description

I have a dialogue bubble, 
![image](https://github.com/user-attachments/assets/5e51e5bd-861c-4298-8415-9fc3f5674d04)

Set the opacity to 0 when they on created
![image](https://github.com/user-attachments/assets/104df877-5bc6-4cd2-bfa0-69c45661c592)

## Attach a .c3p

[issue-childobj-opacity.c3p.zip](https://github.com/user-attachments/files/16613580/issue-childobj-opacity.c3p.zip)

## Steps to reproduce
1. preview, click mouse any key
2.
3.

## Observed result

the 'DialogBubble' object does not appear together
![image](https://github.com/user-attachments/assets/c5d9e6af-57f0-4d71-96e8-e7edff1d0cec)

## Expected result

toggle disable event 2, and preview agine
![image](https://github.com/user-attachments/assets/68f46433-a68f-43a7-8a60-99c15cd1d93d)

## Other Expected

![image](https://github.com/user-attachments/assets/272b4537-8987-42d2-9448-c756fec9f064)

Although this is not the topic of this issue, I would like to say. Is there any way to make them appear as a whole instead of like this?

[UsingLayerGroupMultiChildObjectOpacity.c3p.zip](https://github.com/user-attachments/files/16615195/UsingLayerGroupMultiChildObjectOpacity.c3p.zip)

![image](https://github.com/user-attachments/assets/456581ee-8553-4fa6-a614-7ecdf5da24dd)

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by XHXIAIEIN** [comment]
oh, i see. This is the current by design. If I set the opacity of a child object to 50, then the opacity cap of the child object will also be 50 because it is scaled according to the parent object.

**Comment by DiegoScirra** [comment]
I have to look at this more closely to see if there is any problem.

Opacity has the peculiarity among other hierarchy properties in that the final opacity of an instance is made up of the parent instance opacity multiplied by it's own opacity value. When you set the opacity of a given instance you are modifying the **local** opacity and then that value is used to calculate the final opacity.

**Comment by DiegoScirra** [comment]
The opacity of the child is being produced properly, the problem is the part where the images overlap. In that area the final colour is a blend of both images. If both images have an opacity of 0, there is no problem because the result is fully transparent, if both images have an opacity of 100 it's not a problem either because the result is fully opaque. If both images have any other opacity though, the final colour in the overlapping area will always be more opaque that the two individual images.

So this isn't a bug, it's just how colour blending works.

A workaround for this particular case might be to have the tail of the speech bubble not overlap with the bubble itself or make it so it is transparent in the part where it overlaps.
