### ISSUE TITLE
9Patch object doesn't render when Vulkan is enabled.

### ISSUE THREAD

**Issue by NickR-Git** [Scirra/Construct-bugs#8181]
## Problem description

GPU performance is greatly improved when forcing Vulkan as the renderer on supported systems. However, 9Patch Objects don't render in NWJS exports when Vulkan is enabled through package.json args --use-vulkan and --enable-features=Vulkan.

All other object types appear to render correctly, this issue is strictly with 9-Patch objects.

## Attach a .c3p

[9Patch_VulkanBug_01.zip](https://github.com/user-attachments/files/16651010/9Patch_VulkanBug_01.zip)

## Steps to reproduce

1. Open the .c3p
2. Export to NWJS, add args --use-vulkan --enable-features=Vulkan (also happens with just the second arg used, the first is only included for testing purposes)
3. Run the project
4. Export to NWJS again, without the Vulkan args
5. Observe correct result

## Observed result

The 9patch object doesn't render when Vulkan is enabled.

## Expected result

The 9patch object to render when Vulkan is enabled.

**Comment by AshleyScirra** [comment]
It's not feasible for us to support bugs that only happen when you set specific Chromium command-line arguments. There are hundreds of possible command-line arguments, many of which are designed for development and testing purposes only. If you make use of such features it is unsupported and nobody will be able to help you.

In this case the problem is likely a graphics driver bug anyway, or perhaps a known issue in the Chromium browser engine; perhaps Chromium knows about this and so chooses not to enable Vulkan, but then if you force it enabled anyway you will run in to those known problems. In such cases the cause of the problem is that you used a command-line argument to put Chromium in to a broken mode, and so the fix is to not do that.

**Comment by NickR-Git** [comment]
The issue occurs in the same way across all supported desktop platforms, including GPUs from multiple hardware vendors. The only issue in all cases is 9Patch objects not rendering. This precludes the likelihood that it is a bug related to graphics drivers, unless your suggestion is every hardware vendor is doing it wrong.

It's a command-line argument to enable a more efficient renderer to greatly improve performance, which it does - outside of this one bug. There is a command line field on NWJS export. What do you expect it to be used for?

**Comment by AshleyScirra** [comment]
Perhaps it's a known bug in the Chromium browser engine then. The fact remains Chromium's default settings are designed to choose settings that work. If you force it to use different settings, maybe those settings don't work, which is why Chromium didn't use them. So don't force Chromium to use different settings.

> There is a command line field on NWJS export. What do you expect it to be used for?

You can use it for whatever you want, but it doesn't mean it's supported. It's there partly for development, diagnostic and testing purposes, and doesn't mean anything you do is supported or a sensible thing to do for a published project.
