### ISSUE TITLE
User media non-functional on modern Android

### ISSUE THREAD

**Issue by technofou** [Scirra/Construct-bugs#8206]
## Problem description

User media is unable to get the camera feed for Android 14 devices. The camera feed is black.

## Attach a .c3p

Exporting the official User Media Camera example project from Scirra.

## Steps to reproduce

1. Take the official User Media Camera example project
2. Export with Cordova
3. Run on the latest Pixel or Galaxy device

## Observed result

"Camera 0 ()" is listed with no other option although there is more than one camera available on those devices. Pressing the "Get camera" button shows a "Declined!" response with no alter, notification, window or permission screen shown to the user on the device.

## Expected result

Either the camera feed to appear or a user permission request.

## More details

This issue was reported nearly a year ago with Issue #7716where newer Galaxy devices running OneUI 4 and 5 experienced the issue. The official response from Scirra was that since it was isolated on newer Galaxy devices and it worked on an outdated unsupported Galaxy S8, nothing required to be fixed. We shelved that project waiting for a fix.

Retesting the User Media example today, not only is it still non-functional on modern Galaxy devices (tested on a Z Flip5, Z Flip 6, S22 Ultra, S23 Ultra, S20 Ultra) it is also non-functional on the latest Pixel Android devices (tested on Pixel 9 and Pixel 9 Pro Fold)

This is now a major issue with Construct 3 being incompatible with not just all new Galaxy Android devices, but all new Android devices.

We did a test project with Godot and Unity and they both successfully accessed the camera; this is a Construct 3 issue.

**Affected browsers/platforms:** 

Android 14 devices

**Comment by AshleyScirra** [comment]
We now have a Samsung Galaxy S24 in the office running Android 14 with OneUI v6.1. It works fine for me. In the previous issue #7716 I also tested a couple of other devices, including a much older Samsung device, and they all worked too.

Note you must export the 'Camera input' sample with microphone permission enabled as well, as it requests microphone permission so it can include sound with recordings. If I export with only camera permission enabled and not microphone permission enabled, then I can reproduce the problem that it shows "Declined!" and a blank camera input, but this is because the app requested microphone permission when the app was exported with no such permission allowed. With the correct permissions set, it appears everything is working fine.
