### ISSUE TITLE
IOS v16 and below do not work on releases above r399 and above

### ISSUE THREAD

**Issue by q3olegka** [Scirra/Construct-bugs#8236]
My iphone 6s 15.8.2 version does not display the game release r399 and higher
And it doesn't even depend on the browser, game in chrome also doesn't work on the iphone.

Since I don't have any other phones on IOS, I also checked through browserstack.com shows that iphone versions below v17 are not working

You can check the phone using these links:
https://q3olegka.com/demo/r399/
there is a black screen here

https://q3olegka.com/demo/r398-2/
but everything is ok here

## Attach a .c3p

any empty project version r399 and higher. The game does not work including in preview and remote preview
[r399 ios.zip](https://github.com/user-attachments/files/17059556/r399.ios.zip)

## Steps to reproduce

Open the link https://q3olegka.com/demo/r399/ on an IOS phone version 16 and below

## Observed result

After loading the game, the game layout does not load. A black screen is displayed

## Expected result

After loading the game, the game layout should load

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It turns out the detection of certain CJK characters for the CJK word wrap feature added in r399 only worked on Safari 16+. I've fixed this so the runtime works on older Safari versions again (older versions will fail to do CJK word wrap correctly, but I think that's an acceptable compromise for compatibility). We'll have an r407.2 stable patch release soon to patch this and a couple of other issues so the current stable release will support older iOS versions again.
