### ISSUE TITLE
IFRAME Navigate to URL doesn't work for Android App Bundle 

### ISSUE THREAD

**Issue by rraffo** [Scirra/Construct-bugs#8256]
## Problem description

IFRAME Navigate to URL doesn't work for Android App Bundle (AAP) built with the Construct Built server
DEBUG APK still works

## Attach a .c3p

[iframe_bug.zip](https://github.com/user-attachments/files/17175376/iframe_bug.zip)

## Steps to reproduce

1. export android version using the following option:
2. 
![image](https://github.com/user-attachments/assets/dd6bf412-2fa3-4d37-914d-873561e2a6e7)
![image](https://github.com/user-attachments/assets/f36f68c1-d838-4019-bc48-f7ead048083e)

3.
4.

## Observed result

the IFRAME window is blank 

## Expected result

I'm expecting to see the web page 

## More details
Construct version R408
Chrome Version 129.0.6668.58 (Official Build) (64-bit)

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
The fact it works in a debug APK means Construct's code is working - if it doesn't work in an AAB I suspect it's because of tighter security controls in Android. So you will probably need to do something to configure the app to allow access to external content. FWIW Construct already specifies `<access origin="*" />`, `<allow-intent href="https://*/*" />` and `<allow-navigation href="https://*/*" />` in Cordova's config.xml which ought to permit external resources to be loaded, so presumably something else outside of Construct/Cordova's control is blocking it - perhaps you need to set up something on the Google Play side.

**Comment by rraffo** [comment]
I think I've found the reason. It looks that I have the problem in the Android 7.0 (Samsung S6) version only. Unfortunately I can't test it on other Android 7.0 devices. Are you able to check it? thanks
