### ISSUE TITLE
Performance drop since version r390

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-bugs#8259]
## Problem description

There has been a drop in performance in r390 and all later versions.
Some projects are affected more than others. I couldn't find what exactly is causing it, seems like events are generally running a bit slower.

## Attach a .c3p

These are the official Construct examples where I copy-pasted the events a few times.

[PerfTest1.zip](https://github.com/user-attachments/files/17190018/PerfTest1.zip)
[PerfTest2.zip](https://github.com/user-attachments/files/17190019/PerfTest2.zip)

## Steps to reproduce

1. Run in debug mode in r389 and r390, preferably on a low-end PC. 
Don't press anything, just compare the performance. 

## Observed result

![image](https://github.com/user-attachments/assets/6eefb52e-3fe2-4f87-b39c-a8c2caf32ce2)

And here are two previews running side by side, displaying FPS and CPU utilization:

![image](https://github.com/user-attachments/assets/025f5b83-6936-4f6f-adb8-90a4f0473866)

## Expected result

Same or better performance.

## More details

**First affected release:** r390 and all later versions are affected.

**Comment by F3der1co** [comment]
wtf, I can confirm this unlimited full framed 400 fps R389 and 130 fps on R408

**Comment by dop2000** [comment]
@F3der1co Do you have a personal project to test? 
Our project is still in version r368. I wanted to test how it runs with the recent hierarchy optimizations. And was shocked to see 20-30 fps drop in some locations.
![image](https://github.com/user-attachments/assets/4fd44388-40a5-4f9d-9b2e-7f789144ecd2)

**Comment by F3der1co** [comment]
my main project uses features newer than r389 sadly, so I can't easily role it back to test

**Comment by shotgunanaconda** [comment]
I've also noticed this but thought it was my imagination or new code that i added. Sadly I too cant revert that far back to test it.

**Comment by AshleyScirra** [comment]
Please take note of the [warning about CPU measurements in the manual](https://www.construct.net/en/make-games/manuals/construct-3/interface/debugger/profile-tab). Timer-based CPU measurements are inherently unreliable and so readings like the ones you've reported may well be misleading. It's entirely possible that r390 is actually *faster*, and that allows some CPUs to drop in to a lower frequency lower power mode, which then means they take longer to get the same work done, which produces a *higher* timer-based CPU reading. To avoid being confused or misled by such issues, it is only worthwhile to benchmark performance when running the system as fast as possible (i.e. a difference in iterations per second when running at 100% CPU).

FWIW I can't reproduce any meaningful CPU difference between r389 and r390 on my desktop PC using the stock 3D Castle Maze example, and copy-pasting events multiple times is not a meaningful thing to do and so not something we'd be interested in optimizing. In the code logs, there is nothing that should have significantly affected runtime performance at all between r389 and r390 which further suggests a misleading measurement. If you want us to further investigate such issues, please submit a minimal repro with realistic event sheet logic that that runs the system at 100% CPU and measures iterations per second rather than CPU usage.

**Comment by F3der1co** [comment]
I tested with unlimited full frames, to quote myself : `wtf, I can confirm this unlimited full framed 400 fps R389 and 130 fps on R408 (double checked it didn't switch to webGPU)`

**Comment by F3der1co** [comment]
Also Dop2000 clearly states that is a problem noticed in a real project.

**Comment by dop2000** [comment]
@AshleyScirra 
Here is a new project based on the stock Maze example. I changed only event #5 and #7. 

[PerfTest5.zip](https://github.com/user-attachments/files/17192496/PerfTest5.zip)

![image](https://github.com/user-attachments/assets/9f74f543-9562-4041-b4c2-1ca61c6e906c)

400% difference!

**Comment by F3der1co** [comment]
![image](https://github.com/user-attachments/assets/132f3edf-7a88-44a4-9648-0318c67afdaa)
I am not sure how much to trust the chrome perf profiler, but it seems like GetX and GetY are way heavier on r389

**Comment by dop2000** [comment]
@AshleyScirra Thank you.
And it won't be fixed in the LTS version again, I assume?

**Comment by MikalDev** [comment]
@dop2000 I know where you are coming from on this LTS comment.

I assume it will be fixed in LTS, otherwise I don't understand the point of having a LTS.

**Comment by dop2000** [comment]
I think r409 is still slower than r389
![image](https://github.com/user-attachments/assets/f70f1a0a-0866-4b36-b658-ccab360ba1d8)

**Comment by F3der1co** [comment]
I hope this isn't the encapsulation that adds additional layers of abstraction that hurt performance across the board.

**Comment by AshleyScirra** [comment]
We will likely patch the current stable and LTS versions with this change, but not immediately. Every change carries a risk of regression or unexpected consequences, and so we will leave this change on the beta channel for a few weeks to establish some degree of confidence it has not caused any other side-effects.
