### ISSUE TITLE
Renaming var says it's already used, copy pasting code about that var says it's not there

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-bugs#8274]
## Problem description

![image](https://github.com/user-attachments/assets/4dca29d2-5058-4ba9-93c1-b95b086624a4)

I copy pasted the var L_TokenCount. It created L_TokenCount2. I tried to rename it to L_TokenCount and said it's already used in this scope, which is wrong. I tried copy-pasting the 2 actions related to L_TokenCount to see if that was true somehow, it said this variable doesn't exist. So L_TokenCount was not used in that scope.

## Attach a .c3p
[Variable bug (2).c3p.zip](https://github.com/user-attachments/files/17276255/Variable.bug.2.c3p.zip)

## Steps to reproduce

Recorded here: https://streamable.com/4mf0ts

1. try to rename L_TokenCount2 to L_TokenCount
2. that won't work, next try to copy these actions lower
![image](https://github.com/user-attachments/assets/93b4c9a0-1f9b-4882-bb3d-9ef2e966bbfb)

## Observed result

Doesn't work

## Expected result

I'd expect it when I copy-pasted L_TokenCount outside of its scope to not have it renamed to L_TokenCount2.

## More details

**Affected browsers/platforms:** Latest Chrome on Win 10

**First affected release:** just noticed it now in 405.2

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r407.2 (stable)
Browser: Chrome 129.0.6668.89
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 32
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 1006 gb
Storage usage (approx): 435 mb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3070 (0x00002488) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_clip_control
EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_conservative_depth
EXT_depth_clamp
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_polygon_offset_clamp
EXT_render_snorm
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_mirror_clamp_to_edge
EXT_texture_norm16
KHR_parallel_shader_compile
NV_shader_noperspective_interpolation
OES_draw_buffers_indexed
OES_sample_variables
OES_shader_multisample_interpolation
OES_texture_float_linear
OVR_multiview2
WEBGL_blend_func_extended
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_polygon_mode
WEBGL_provoking_vertex
WEBGL_stencil_texturing
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm;codecs=opus)
WebM Vorbis (audio/webm;codecs=vorbis)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav;codecs=1)
Supported encode formats:

WebM Opus (audio/webm;codecs=opus)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
Video information
Supported decode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 H.265 (video/mp4;codecs=hev1.1.2.L93.B0)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
Supported encode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
WebM H.264 (video/webm;codecs=avc1.420034)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 VP9 (video/mp4;codecs=vp9)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)

</details>

**Comment by AshleyScirra** [comment]
It is actually correct Construct prevents you renaming the variable in this case. The scope of `L_TokenCount2` is in fact its entire indent level - it's not just from where its block is and below. For example in the further-indented event 6, you can make an action like 'Set L_TokenCount to L_TokenCount2', which is valid and by design. This then illustrates the problem if you are allowed to rename `L_TokenCount2` to `L_TokenCount` - it would make references to the name `L_TokenCount` ambiguous as it could refer to two variables. In other words the scope of `L_TokenCount2` "shadows" the scope of `L_TokenCount` so cannot be renamed to use the same name.

AFAIK different programming languages have different rules about scope in this kind of situation, but here's an analogous example using JavaScript: the reference to `myvar` is allowed even before its declaration, so long as the code is actually executed after the variable declaration line is executed.

```js
function outer()
{
    function inner()
    {
        console.log(myvar);
    }

    let myvar = 1;

    inner();
}
```

As per JavaScript's temporal deadzone (TDZ) rules, you can write code that references `myvar` before its declaration and also executes that code before its declaration, but that will throw a ReferenceError ("Cannot access 'myvar' before initialization") - Construct does not implement anything equivalent to this and just allows it, which is more like `var`, but in JavaScript `var` is always function-scoped, so it's not a perfect analogy. Construct is more like half way between the two with its event variables.
