### ISSUE TITLE
Overlapping audio with the same tag causes audio distortion

### ISSUE THREAD

**Issue by bobatealee** [Scirra/Construct-bugs#8281]
## Problem description

When playing the same audio file with a tag several times in quick succession, the audio becomes distorted. This issue worsens with variable playback rates or playing audio through timelines. This issue does not happen to untagged audio.

## Attach a .c3p

[tagged_audio_bug.zip](https://github.com/user-attachments/files/17332790/tagged_audio_bug.zip)

## Steps to reproduce

1. Click the buttons, which will play some audio files in quick succession.
2. Click "Toggle Random Speed" to enable variable playback rate of the next audio you play.

## Observed result

"No tag" and "No tag (Timeline)" will sound correct under all circumstances. 

"Tag" and "Tag (Timeline)" will sound choppy when played. "Toggle Random Speed" worsens the effect and and causes jitteriness.

## Expected result

I expected tagged audio to behave identical to untagged audio, as the only thing I'm aware of audio tags being used for is controlling volume, playback rate, and other effects that are meant to only target specific audio files.

## More details

**Affected browsers/platforms:** Google Chrome 128.0.6613.138 (x64), Mozilla Firefox 130.0.1 (x64)

**First affected release:** r407

## System details

<details><summary>View details</summary>

Platform information

Product: Construct 3 r407.2 (stable)
Browser: Firefox 131.0
Browser engine: Gecko
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 16
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:131.0) Gecko/20100101 Firefox/131.0
Language setting: en-US
Local storage

Storage quota (approx): 931 gb
Storage usage (approx): 738 mb (0.1%)
Persistant storage: Yes
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to [bug 1163426](https://bugzilla.mozilla.org/show_bug.cgi?id=1163426)
    Determining input device capabilities is not supported.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 980 Direct3D11 vs_5_0 ps_5_0), or similar
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_bptc
    EXT_texture_compression_rgtc
    EXT_texture_filter_anisotropic
    OES_draw_buffers_indexed
    OES_texture_float_linear
    OVR_multiview2
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context
    WEBGL_provoking_vertex

Audio information

System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm;codecs=opus)
    WebM Vorbis (audio/webm;codecs=vorbis)
    MPEG-4 Opus (audio/mp4;codecs=opus)
    MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav;codecs=1)

Supported encode formats:

    WebM Opus (audio/webm;codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm;codecs=av01.0.00M.08)
    WebM VP9 (video/webm;codecs=vp9)
    WebM VP8 (video/webm;codecs=vp8)
    MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
    MPEG-4 VP9 (video/mp4;codecs=vp9)
    MPEG-4 H.264 (video/mp4;codecs=avc1.420034)

Supported encode formats:

    WebM VP8 (video/webm;codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I can't hear any difference between any four of the buttons unless I check 'Toggle random speed'. When it is enabled it does sound a bit weird, but changing the playback speed of a sound is a tricky digital audio effect which can sound a bit odd, and so when you stack multiple sounds with different playback speeds, I think you get some weird aliasing effects. Even without changing the playback speed, playing lots of identical sounds in quick succession can cause phasing effects, but that's normal with digital audio.

As far as I'm aware both normal playback, tags, and setting the playback rate, all work correctly - I think you're probably just hearing something weird caused by stacking lots of similar sounds, but that's just how digital audio works and isn't a problem with Construct itself. If you think there is a problem with any particular feature, you can try reporting it with a minimal repro focused on just that, but if it involves lots of sounds played close together in time and your only feedback is "it sounds weird", then I think our only response can be "yep, that happens sometimes".

**Comment by bobatealee** [comment]
> I can't hear any difference between any four of the buttons unless I check 'Toggle random speed'. When it is enabled it does sound a bit weird, but changing the playback speed of a sound is a tricky digital audio effect which can sound a bit odd, and so when you stack multiple sounds with different playback speeds, I think you get some weird aliasing effects. Even without changing the playback speed, playing lots of identical sounds in quick succession can cause phasing effects, but that's normal with digital audio.
> 
> As far as I'm aware both normal playback, tags, and setting the playback rate, all work correctly - I think you're probably just hearing something weird caused by stacking lots of similar sounds, but that's just how digital audio works and isn't a problem with Construct itself. If you think there is a problem with any particular feature, you can try reporting it with a minimal repro focused on just that, but if it involves lots of sounds played close together in time and your only feedback is "it sounds weird", then I think our only response can be "yep, that happens sometimes".

I'm not sure I understand your approach to the issue. There is a clear inconsistency with the way it works when the audio is tagged vs. untagged, as seen in the example project - that is the bug. I've tested this across Firefox and Chrome and it happens in both consistently *only* when the audio is tagged.

**Comment by AshleyScirra** [comment]
I'm afraid it's still not clear to me what you're expecting it to sound like instead. As the test project modifies some sounds by their tag, it seems entirely possible it is working correctly, and that it sounds differently with a tag vs. no tag as it is modifying different sounds depending on the tag. Part of the problem is the project isn't really a minimal repro - it has lots of events and combinations and indirection through a sprite that make it harder to tell what it's meant to be doing vs. what it is doing. So far I don't yet see any evidence of a bug in Construct, but if you want us to investigate further, you can file another issue using a minimal project (ideally <5 events and ~1 object).
