### ISSUE TITLE
Speech synthesis 

### ISSUE THREAD

**Issue by ADAMLUKEGOODWIN** [Scirra/Construct-bugs#8290]
## Problem description

Hi,

Got a classroom of 16 pcs. Latest chrome update seems to have stopped speech synthesis. Works in other browsers.

Let me know please if you have the same issue.

## Steps to reproduce

Try to make it speak

## Observed result

It won't speak

## Expected result

It should speak

## More details

**First affected release:** 
It seems to be a chrome update - my old c3 builds no longer speak with chrome's built in tts

## System details

Tried on all the computers in my school. It slowly started happening one by one. This tells me it was a chrome update that stopped the plugin from working.

**Comment by AshleyScirra** [comment]
Using the [Speech Synthesis example](https://editor.construct.net/#open=speech-synthesis), for me I get the following results:

- Chrome 130.0.6723.70 (stable): 'speak' button does not work
- Chrome 131.0.6778.13 (beta): works OK
- Chrome 132.0.6797.0 (canary): works OK

We haven't changed anything about how Speech Synthesis works, so it looks a lot like a Chrome bug that's already been fixed in v131. [This bug](https://issues.chromium.org/issues/374263394) looks related and indeed in v130 if I change the voice to Google US English before pressing 'speak' it does work, so it might be some problem with trying to play a default Microsoft voice.

Can you confirm it works for you in Chrome beta v131 or newer?

**Comment by ADAMLUKEGOODWIN** [comment]
Hi Ashley,

Yes wonderful. It works in chrome 
Version 131.0.6778.13 (Official Build) beta (64-bit)

All voices working as hoped. 

Thanks! It is a Chrome bug that will go away by itself then! 

Have a great day.

**Comment by AshleyScirra** [comment]
Thanks for confirming. Closing this issue as it appears to be a Chrome bug that is fixed in v131+.

**Comment by ADAMLUKEGOODWIN** [comment]
Great! 
The roadmap was useful, as we could tell our students and their parents, when they can stop using edge, and go back to Chrome! 
Thank you for the quick response and troubleshooting.
