### ISSUE TITLE
r413 Browser "close" action freezes the game, instead of closing it, at least with NJWS

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-bugs#8301]
Browser "close" action freezes the game, instead of closing it, at least with NJWS

see #8221 

![image](https://github.com/user-attachments/assets/9b9110a7-1668-4ed3-a053-99e14ff70ce0)

Seems to happen with any game, not just mine, because even adding that action to Kiwi Story, made it freeze like this, instead of closing:

![image](https://github.com/user-attachments/assets/869a97ea-d9b8-472c-b5ab-dd61275d9982)

I was using latest NWJS build too

**Comment by AshleyScirra** [comment]
Minimal repro as none was provided: 
[issue8301.zip](https://github.com/user-attachments/files/17571464/issue8301.zip)

**Comment by AshleyScirra** [comment]
This seems to be a weird issue caused by the workaround to #8221. I have no idea why it happens and it doesn't seem possible to debug it as devtools gets closed but the main window is left open. I've found a workaround to the workaround and added that for the next beta, so hopefully that works - but it's no surprise that adding workarounds instead of fixing the root cause issue ends up causing more weird problems, so I'd still recommend someone reports the problem directly to NW.js like I [originally recommended](https://github.com/Scirra/Construct-bugs/issues/8221#issuecomment-2352913218) to try to get the root cause problem fixed. Or move to one of our newer export options as in the long term we plan to phase out NW.js.
