### ISSUE TITLE
NW.js icon replacer doesn't work for .exe

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#8309]
## Problem description
NW.js icon replacer doesn't work correctly, tested on windows 11 with NW.js v0.93.0, Chromium 130, Construct 3 r413

## Attach a .c3p
NWjs export is  too large, so it's just an empty project with icons changed:
[iconDebug.zip](https://github.com/user-attachments/files/17598803/iconDebug.zip)

## Steps to reproduce

1. export project to NW.js
2. extract and run the windows_icon_replacer

## Observed result
on the .exe file it's not working (I tried refreshing and restarting the computer, to make sure it's not some cache issue)
![image](https://github.com/user-attachments/assets/153c560e-bb9f-4d0c-b0ac-d4264db2fd21)
window and task bar does work
![image](https://github.com/user-attachments/assets/80fae7a1-4f33-4610-836e-b293471a7ea8)

## Expected result
Icon is replaced on the executable too.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by F3der1co** [comment]
Issue seems to exist on win 10 and stable too, according to other user.

**Comment by AshleyScirra** [comment]
It looks like the problem is specific to the NW.js 0.93 release: the way icons are stored in the executable has changed, and a stock icon now ends up taking precedence over the Construct icons even after running WindowsIconUpdater.exe. I've fixed this for the tool but the deployment will be delayed because as this tool is so infrequently updated, the code signing certificate for it has expired, so I need to go through a round of renewing that which can take a while before deploying the updated tool.

In the mean time you can work around this using [Resource Hacker](https://www.angusj.com/resourcehacker/):

1. Export to NW.js and extract files somewhere
2. Use Resource Hacker to open the NW.js executable file
3. Delete everything under the "Icon group" category
4. Save the modified executable in Resource Hacker and close Resource Hacker
5. Now run WindowsIconUpdater.exe - it should set the correct icon.

**Comment by AshleyScirra** [comment]
I finally got the code signing sorted out so an updated WindowsIconUpdater.exe tool will be shipping in the next beta release.
