### ISSUE TITLE
Strange anchor behavior when window is resized

### ISSUE THREAD

**Issue by Dramamini** [Scirra/Construct-bugs#8323]
I have some buttons in my UI and I am using anchor behavior to keep them in place when window is resized. It is working. The problem starts when i want to "beautify" a user click, for example to make a button change size when user presses it. If user hasn't changed the dimensions of the viewport, anchor behavior is working as it should, but if user change window size, in this situation, anchor starts a strange behavior as I show you later in this report.

[AnchorProblem.zip](https://github.com/user-attachments/files/17724242/AnchorProblem.zip)

## Steps to reproduce

1. Press the white square buttons, everything is working as expected
2. Resize window
3. Anchor starts a strange behavior
4. Close preview window & try again
5. Another strange behavior is noticed

## Observed result

https://github.com/user-attachments/assets/fc44946c-986c-4ca4-8ba2-4053e632e9ec

## Expected result

Changing the size of an object that has the anchor behavior, to work with any window size

## More details
A workaround that have found is to use two objects one above another linked with hierarchy and enable anchor behavior only to the back object so i can change the size of the front object while keeping it's place but i think it is a complicated method. It would be nice and clear if anchor behavior could work even if window is resized.

Chrome, Windows

**First affected release:** It's been a long time I think

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r415 (beta)
Browser: Chrome 130.0.6723.117
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 559 gb
Storage usage (approx): 1.7 gb (0.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce G105M (0x00000A68) Direct3D11 vs_4_1 ps_4_1, D3D11)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 1024
Extensions:

EXT_clip_control
EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_depth_clamp
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_polygon_offset_clamp
EXT_render_snorm
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_mirror_clamp_to_edge
EXT_texture_norm16
KHR_parallel_shader_compile
NV_shader_noperspective_interpolation
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_blend_func_extended
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_polygon_mode
WEBGL_provoking_vertex
WEBGL_stencil_texturing
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm;codecs=opus)
WebM Vorbis (audio/webm;codecs=vorbis)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav;codecs=1)
Supported encode formats:

WebM Opus (audio/webm;codecs=opus)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
Video information
Supported decode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
Supported encode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
WebM H.264 (video/webm;codecs=avc1.420034)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 VP9 (video/mp4;codecs=vp9)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)

</details>

**Comment by AshleyScirra** [comment]
This is actually by design. Part of the problem is it's difficult to see at runtime what it's anchoring relative to - this project demonstrates it more clearly by highlighting the *original* viewport area yellow: [issue8323.zip](https://github.com/user-attachments/files/17732109/issue8323.zip)

When you disable and re-enable the Anchor behavior it reinitializes its offsets, and it always uses the original viewport area - highlighted yellow - to identify its offset, just as it does on startup. Further, the project uses 'Scale outer' fullscreen mode, which is important, as it changes the visible viewport area. So initially with the view exactly aligned to the yellow area, disabling and re-enabling the Anchor behavior works normally. Resize the window a little wider though and now the viewport is wider than the original area; disable and enable the Anchor behavior and it then determines its offset relative to the yellow area - which it is now further to the left of - and then it applies that offset to the current viewport, which moves itself further to the left of that.

Perhaps this could be changed but this will likely immediately run in to two problems: firstly I believe there are other use cases where people expect 'Set enabled' to do the same thing it does on startup, so it needs to work like it does already; and secondly changing this would likely be a breaking change to 10+ years of projects using this behavior. Really the Anchor behavior only works well for simple cases, and despite what it looks like this is not that simple a case - for more advanced cases just use the system viewport expressions, which is almost as simple and easier to reason about, like this: 
[issue8323-workaround.zip](https://github.com/user-attachments/files/17732228/issue8323-workaround.zip)
