### ISSUE TITLE
Script in C3: Function setReturnValue does not handle Boolean values ​​correctly

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#8341]
## Problem description

We often need to compare something with the help of script in function and then use it in a condition or expression.

However, C3 function in eventSheet cannot return Boolean, only numbers. If use the `runtime.setReturnValue(true);` in JS, it cannot handle it correctly.

![image](https://github.com/user-attachments/assets/5685586d-c3c7-411f-b592-974fd6301c7a)

## Attach a .c3p

[issue-function-setReturnValue-bool.c3p.zip](https://github.com/user-attachments/files/17968447/issue-function-setReturnValue-bool.c3p.zip)

## Steps to reproduce

1.
2.
3.

## Observed result

```js
runtime.setReturnValue(true); //  return 0
``` 

```js
runtime.setReturnValue(true ? 1 : 0); //  return 1
``` 

## Expected result

```js
runtime.setReturnValue(true);  //  return 1
runtime.setReturnValue(false); //  return 0
``` 

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is by design: the event system does not have a boolean type, and so you cannot actually return a boolean from a function. The allowed function return types are number, string, and any (meaning either number or string). Your screenshot shows a function returning a number, and so you must provide a number, either via the event sheet or script.

It might seem an obvious change to allow returning a boolean and convert that to 0 or 1 automatically, but that could complicate things if we ever add support for a boolean type in the event system in future. Suppose a future release of Construct has support for actually returning booleans from functions; then we might have to change what passing a boolean to `setReturnValue` means, and that could break existing projects. So I'd rather keep the type check strict so it's future-proof.
