### ISSUE TITLE
Webview2's FileSystem does not work in lower versions, but can be checked-in for features support conditions

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#8356]
## Problem description

if the user's webview2(or Edge brower version) is still in an old version and has not been automatically updated for some reason, if the Construct game uses features such as fileSystem that rely on webview2, the file reading and writing functions may not work properly. Even if the Desktop features supported and Is supported conditions of FileSystem return true,

## Attach a .c3p

Made by Potion:
[FilesystemPickTag.c3p.zip](https://github.com/user-attachments/files/18136280/FilesystemPickTag.c3p.zip)

## Steps to reproduce

export and run in webview2

## Observed result

Edge version 131.0.2903.86 
![image](https://github.com/user-attachments/assets/1b2d0fdd-1d2d-40a2-ad0c-3987662eb2f4)

webview2 runtime version 126.0.2592.81
![a1066cfe6a4640ffaaa4359e3a855651](https://github.com/user-attachments/assets/0523b9bc-4a78-490d-ab13-ca1a1aed3cf3)

![52b4f27cba27c03b386a70e5caf64221](https://github.com/user-attachments/assets/d25e4f75-3677-4c10-ab5d-c1bd148adcdc)

After this user downloads the latest version of webview2 from [Microsoft's official website](https://developer.microsoft.com/en-gb/microsoft-edge/webview2/), it can work normally

## Expected result

The export packager will verify the player's Edge version and prompt the player to upgrade if the version is lower than a certain value.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Internally the File System known folder integration does handle old versions of WebView2 and does not return known folder picker tags if it's not supported. So you can detect this by whether the picker tags are available. Technically there are other reasons known folders are not available (e.g. perhaps they don't exist, permission was denied, or the system is otherwise configured differently), but I think the basic folders like Documents should always be available, and so you can use the availability of that picker tag to identify an out-of-date webview from your project. 'Desktop features supported' covers other features like 'Shell open' and 'Run file' which do still work with out-of-date webviews, and so is not the right condition to check whether known folders are available. I don't think the wrapper app can easily identify what version a project really needs (some projects might not use known folder picker tags), so it's not really in a position to automatically notify the user.

The support for known folders is based on a fairly recent addition to WebView2, and from the docs I think it requires v127+ which came out around July. Your screenshot shows v126 so it's only just out of date. WebView2 is meant to auto-update and so in the long term this should not be a problem. I don't know why a system would have WebView2 out of date - I guess maybe the system went offline for a long time, or ran out of storage or something. But basically this is all working as designed and I don't think there's much to be done about this other than make your project notify users itself, and eventually virtually everyone will be updated to a version that supports known folders and then this won't be a problem any more.
