### ISSUE TITLE
Implement reverse Z for better depth precision

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#8357]
## Problem description
In c3 there are multiple depth related issue, including frequent z-fighting (sometimes requiring large z-elevation differences if the camera is further away)  and also huge depth precision issues on mobile (#5510 #7899)

Implementing reverse Z/reverse depth mapping should greatly improve those issues, see: https://developer.nvidia.com/content/depth-precision-visualized
excerpt:
![image](https://github.com/user-attachments/assets/40700f3c-ca28-46b2-9ec1-71c00f8225c4)

## Attach a .c3p
if needed I can make a sample of z-fighting and depth on mobile, but I think you are aware already

## Observed result
z-fighting, depth precision issues particualarily on mobile with webGL.

## Expected result
less z-fighting, higher precision

## More details
I am reporting this as a bug instead of a suggestion as I am expecting it to fix or at least improve these bugs #5510 #7899.

This will probably require changes in built-in shaders and also third party shaders. But this is not a big issue imho as there aren't many depth based effects and for third party it afaik only affects Mikal and me, and I'm sure we can manage.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by F3der1co** [comment]
another blog post talking about it that may be interesting
https://tomhultonharrop.com/mathematics/graphics/2023/08/06/reverse-z.html

**Comment by skymen** [comment]
As an added precision, these Z related issues have been affecting us a lot on our game Under The Red Sky if you need an example of these problems happening in the wild.
https://poki.com/en/g/under-the-red-sky

Also, Construct isn't very thoroughly equipped to let us deal with Z fighting issues. Since 3D shapes don't support mesh distort and it's very tedious to use 3D models for level design, we're left having to use a lot of overlapping shapes and the only solution we have to fight it as Federico says is moving objects on the Z axis but there's only so much moving we can do before it affects the level design in undesirable ways.

**Comment by F3der1co** [comment]
feature request:
https://github.com/Scirra/Construct-feature-requests/issues/407
