### ISSUE TITLE
facebook playable ad black screen 

### ISSUE THREAD

**Issue by rezzonanc** [Scirra/Construct-bugs#8361]
## Problem description
r416-2
Black screen when trying to upload playable ad to Facebook ad campaign. When exporting as zip in the console nothing, but if you export as a single .html - it writes this:
![image](https://github.com/user-attachments/assets/efa17ede-3789-442d-84c6-102e7bb5c697)

## Attach a .c3p
https://drive.google.com/file/d/1URaQhWAtJEzIBCX37KVY3tmv6QWs7dSu/view?usp=sharing

## Steps to reproduce

1. open project
2. build as playable ad
3. upload at facebook ad company 

## Observed result
black screen

## Expected result
playable is working

## More details
**Affected browsers/platforms:** 
chrome

</details>

**Comment by AshleyScirra** [comment]
Those errors are caused by the server configuration. IIRC the Playable Ad test tool was broken - I contacted Facebook to try to get them to fix it but to no avail; you'll need to contact Facebook about that yourself. I would also strongly recommend using the zip format instead of the single file format as it has better compatibility.
